CREATE VIEW emea_consume_ceec.ceec_m360_mapping_final_view (
  bam,
  brand_by_manufacturer COMMENT 'Brand by Manufacturer',
  brand_local_name COMMENT 'Brand Local Name',
  brand_name COMMENT 'Brand Name',
  category_m360,
  category_name COMMENT 'Category Name',
  cc_product_id,
  channel,
  cluster,
  corporation,
  country,
  country_description,
  country_map,
  country_product_local_description COMMENT 'Local Sku Entity',
  currency,
  data_source COMMENT 'Data Source',
  day_of_year,
  form_1,
  general_segment,
  id_version COMMENT 'Version',
  is_brand_produced_by_bayer COMMENT 'Is Brand Produced By Bayer',
  is_m360_country,
  key_main,
  key1,
  key2,
  key3,
  key4,
  load_date,
  local_atc4_description COMMENT 'Local Atc4 Description',
  local_category_name COMMENT 'Local Category Name',
  local_form COMMENT 'Local Form',
  local_ingredient COMMENT 'Local Ingredient',
  local_key_business_category COMMENT 'Local Key Business Category',
  local_otc4_description COMMENT 'Local Otc4 Description',
  local_product_sub_type COMMENT 'Local Product Sub Type',
  local_product_type COMMENT 'Local Product Type',
  local_segment_name COMMENT 'Local Segment Name',
  local_sub_category_name COMMENT 'Local Sub Category Name',
  local_user COMMENT 'Local User',
  manufacturer,
  manufacturer_corporation COMMENT 'Manufacturer Corporation',
  manufacturer_local_name COMMENT 'Manufacturer Local Name',
  market_brand,
  marketing_source,
  nfc1_description,
  nfc1_id,
  nfc12_description,
  nfc12_id,
  nfc123_description,
  nfc123_id,
  otc1_description,
  otc1_id,
  otc2_description,
  otc2_id,
  otc3_description,
  otc3_id,
  otc4_description,
  otc4_id,
  pack,
  pack_description COMMENT 'Pack Description',
  pack_form COMMENT 'Pack Form',
  pack_form_extd COMMENT 'Pack Form Extd',
  pack_size,
  pack_size_group COMMENT 'Pack Size Group',
  pack_size_measure COMMENT 'Pack Size Measure',
  pack_size_str COMMENT 'Pack Size',
  pack_size_value COMMENT 'Pack Size Value',
  peer_group_flag COMMENT 'Peer Group Flag',
  power_brand_flag COMMENT 'Power Brand Flag',
  power_brand_type COMMENT 'Power Brand Type',
  product,
  product_description COMMENT 'Product Description',
  product_id COMMENT 'Id',
  product_local_description COMMENT 'Product Local Description',
  product_type COMMENT 'Product Type',
  projected COMMENT 'Bayer Flag',
  region,
  sales_value,
  sales_volume,
  sam,
  segment_bch COMMENT 'Segment Bch',
  segment_bch_brand COMMENT 'Segment Bch Brand',
  segment_m360,
  segment_name COMMENT 'Segment Name',
  sub_brand_name COMMENT 'Sub Brand Name',
  sub_category_name COMMENT 'Sub Category Name',
  sub_region,
  time_id,
  type_of_the_key,
  uov_factor_rule COMMENT 'Global UoV Factor Rule',
  version COMMENT 'Version',
  week_of_year,
  year,
  year_month,
  year_quarter)
WITH SCHEMA BINDING
AS (
select 
BAM bam,
BRAND_BY_MANUFACTURER brand_by_manufacturer,
BRAND_LOCAL_NAME brand_local_name,
BRAND_NAME brand_name,
CATEGORY_M360 category_m360,
CATEGORY_NAME category_name,
CC_PRODUCT_ID cc_product_id,
Channel channel,
`CLUSTER` cluster,
Corporation corporation,
COUNTRY country,
COUNTRY_DESCRIPTION country_description,
COUNTRY_MAP country_map,
COUNTRY_PRODUCT_LOCAL_DESCRIPTION country_product_local_description,
CURRENCY currency,
DATA_SOURCE data_source,
Day_of_Year day_of_year,
Form_1 form_1,
General_Segment general_segment,
ID_VERSION id_version,
IS_BRAND_PRODUCED_BY_BAYER is_brand_produced_by_bayer,
IS_M360_COUNTRY is_m360_country,
KEY_MAIN key_main,
Key1 key1,
Key2 key2,
Key3 key3,
Key4 key4,
LOAD_DATE load_date,
LOCAL_ATC4_DESCRIPTION local_atc4_description,
LOCAL_CATEGORY_NAME local_category_name,
LOCAL_FORM local_form,
LOCAL_INGREDIENT local_ingredient,
LOCAL_KEY_BUSINESS_CATEGORY local_key_business_category,
LOCAL_OTC4_DESCRIPTION local_otc4_description,
LOCAL_PRODUCT_SUB_TYPE local_product_sub_type,
LOCAL_PRODUCT_TYPE local_product_type,
LOCAL_SEGMENT_NAME local_segment_name,
LOCAL_SUB_CATEGORY_NAME local_sub_category_name,
LOCAL_USER local_user,
Manufacturer manufacturer,
MANUFACTURER_CORPORATION manufacturer_corporation,
MANUFACTURER_LOCAL_NAME manufacturer_local_name,
Market_Brand market_brand,
MARKETING_SOURCE marketing_source,
NFC1_description nfc1_description,
NFC1_ID nfc1_id,
NFC12_description nfc12_description,
NFC12_ID nfc12_id,
NFC123_description nfc123_description,
NFC123_ID nfc123_id,
OTC1_description otc1_description,
OTC1_ID otc1_id,
OTC2_description otc2_description,
OTC2_ID otc2_id,
OTC3_description otc3_description,
OTC3_ID otc3_id,
OTC4_description otc4_description,
OTC4_ID otc4_id,
Pack pack,
PACK_DESCRIPTION pack_description,
PACK_FORM pack_form,
PACK_FORM_EXTD pack_form_extd,
Pack_Size pack_size,
PACK_SIZE_GROUP pack_size_group,
PACK_SIZE_MEASURE pack_size_measure,
PACK_SIZE_STR pack_size_str,
PACK_SIZE_VALUE pack_size_value,
PEER_GROUP_FLAG peer_group_flag,
POWER_BRAND_FLAG power_brand_flag,
POWER_BRAND_TYPE power_brand_type,
Product product,
PRODUCT_DESCRIPTION product_description,
PRODUCT_ID product_id,
PRODUCT_LOCAL_DESCRIPTION product_local_description,
PRODUCT_TYPE product_type,
PROJECTED projected,
REGION region,
Sales_Value sales_value,
Sales_Volume sales_volume,
SAM sam,
SEGMENT_BCH segment_bch,
SEGMENT_BCH_BRAND segment_bch_brand,
SEGMENT_M360 segment_m360,
SEGMENT_NAME segment_name,
SUB_BRAND_NAME sub_brand_name,
SUB_CATEGORY_NAME sub_category_name,
SUB_REGION sub_region,
TIME_ID time_id,
TYPE_OF_THE_KEY type_of_the_key,
UOV_FACTOR_RULE uov_factor_rule,
VERSION version,
Week_of_Year week_of_year,
Year year,
Year_month year_month,
Year_quarter year_quarter
from 
emea_raw_lnd_ceec.vw_ceec_m360_mapping_final_view)