CREATE TABLE chdaa_prd_lz_emea.emea_quality_corr_ceec.esalesweb_organization_rating (
  irda_sys_is_deleted BOOLEAN,
  irda_sys_deleted TIMESTAMP,
  rating_id STRING,
  irda_sys_correlation_id STRING,
  irda_sys_changed_by STRING,
  product_line_id STRING,
  irda_sys_object_guid STRING,
  object_id DECIMAL(20,0),
  irda_sys_country STRING,
  irda_sys_updated TIMESTAMP,
  rating_year STRING,
  computed_rating_value STRING,
  userchanged TIMESTAMP,
  irda_sys_touched TIMESTAMP,
  organization_id STRING,
  createdby STRING,
  sys_source_system STRING,
  changedby STRING,
  irda_sys_created TIMESTAMP,
  client_variant_id DECIMAL(20,0),
  irda_sys_is_dirty BOOLEAN,
  changed TIMESTAMP,
  irda_sys_unique_key STRING,
  deleted FLOAT,
  created TIMESTAMP,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/correction/ceec/esalesweb_organization_rating'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')