CREATE TABLE chdaa_prd_lz_emea.emea_quality_corr_ceec.wdy_pl_products (
  nr_pozwolenia STRING,
  sku_name STRING,
  form STRING,
  sku_short_name STRING,
  vat FLOAT,
  bloz7 INT,
  bazyl INT,
  status STRING,
  is_msl_list STRING,
  product_type STRING,
  brand_group STRING,
  exfactory_price FLOAT,
  is_massmarket STRING,
  is_commercial STRING,
  key_words STRING,
  aktualnosc DATE,
  brand STRING,
  ean BIGINT,
  fct_tool_name STRING,
  is_contracted STRING,
  sap_id INT,
  active_substance_dosage STRING,
  pkwiu STRING,
  sap_name STRING,
  attribute STRING,
  unit_of_measurement STRING,
  category STRING,
  units_volume STRING,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/correction/ceec/wdy_pl_products'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')