CREATE TABLE chdaa_prd_lz_emea.emea_quality_corr_ceec.esalesweb_attribute_selection (
  irda_sys_is_deleted BOOLEAN,
  score FLOAT,
  irda_sys_deleted TIMESTAMP,
  irda_sys_correlation_id STRING,
  irda_sys_changed_by STRING,
  irda_sys_object_guid STRING,
  object_id DECIMAL(20,0),
  irda_sys_country STRING,
  sort_index FLOAT,
  irda_sys_updated TIMESTAMP,
  description STRING,
  userchanged TIMESTAMP,
  irda_sys_touched TIMESTAMP,
  selection_description STRING,
  createdby STRING,
  sys_source_system STRING,
  changedby STRING,
  irda_sys_created TIMESTAMP,
  attribute_selection_id STRING,
  client_variant_id DECIMAL(20,0),
  irda_sys_is_dirty BOOLEAN,
  attribute_id STRING,
  changed TIMESTAMP,
  irda_sys_unique_key STRING,
  deleted FLOAT,
  active FLOAT,
  created TIMESTAMP,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/correction/ceec/esalesweb_attribute_selection'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')