CREATE TABLE chdaa_prd_lz_emea.emea_quality_corr_ceec.farmaprom_product_brand_current (
  Marka_status STRING,
  Produkt_priorytetowy STRING,
  Produkt_status_liczba BIGINT,
  Lek_refundowany_liczba BIGINT,
  Ratujacy_zycie STRING,
  Marka_status_liczba BIGINT,
  Postac STRING,
  Kanal_sprzedazy_liczba BIGINT,
  Nazwa_produktu STRING,
  Produkt_status STRING,
  Data_dodania TIMESTAMP,
  Ratujacy_zycie_liczba BIGINT,
  ATC_Kod STRING,
  Mnoznik BIGINT,
  Kategoria_produktowa STRING,
  Kod_produktu STRING,
  Probka_darowizna_status BIGINT,
  Produkt_priorytetowy_liczba BIGINT,
  Grupa_produktowa STRING,
  Dodatkowa_cena DOUBLE,
  Minimalna_liczba_sztuk_w_zamowieniu BIGINT,
  Miesieczne_standardowe_zapotrzebowanie_apteki STRING,
  Maksymalny_rabat DOUBLE,
  ID_marka_produktu BIGINT,
  Szacunkowa_cena DOUBLE,
  Data_modyfikacji TIMESTAMP,
  ID_producenta BIGINT,
  Kategoria_produktowa_szeroka STRING,
  Limit_na_klienta_na_rok BIGINT,
  Polka_przedstawicielska_liczba BIGINT,
  Kanal_sprzedazy STRING,
  Dawka STRING,
  BLOZ STRING,
  Opis STRING,
  Grupa_produktowa_max_data_modyfikacji TIMESTAMP,
  ID_produktu BIGINT,
  Lek_refundowany STRING,
  Liczba_sztuk_w_opakowaniu_zbiorczym BIGINT,
  Polka_przedstawicielska STRING,
  Rodzaj_produktu_liczba BIGINT,
  EAN STRING,
  ATC_Nazwa STRING,
  ID_kategoria_produktowa BIGINT,
  Marka STRING,
  Probka_darowizna STRING,
  Miesieczne_standardowe_zapotrzebowanie_apteki_liczba BIGINT,
  Probka_darowizna_liczba BIGINT,
  Wielkosc_opakowania STRING,
  Rodzaj_produktu STRING,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/correction/ceec/farmaprom_product_brand_current'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')