CREATE VIEW emea_quality_corr_ceec.vw_dim_products (
  product_id,
  product_bk,
  product_source,
  product_valid_from,
  product_valid_to,
  product_is_valid,
  LastModifiedDate,
  PRODUCT_LAD,
  bloz7,
  ean,
  sap_id,
  sku_name,
  sku_short_name,
  bazyl,
  nr_pozwolenia,
  pkwiu,
  sap_name,
  status,
  brand_group,
  brand,
  Is_Commercial,
  Is_MassMarket,
  Is_MSL_List,
  Is_Contracted,
  category,
  fct_tool_name,
  product_type,
  attribute,
  active_substance_dosage,
  key_words,
  form,
  units_volume,
  unit_of_measurement,
  vat,
  exfactory_price,
  aktualnosc,
  ETLLastModifiedDate)
WITH SCHEMA BINDING
AS (select 
	cast(null as integer)								as product_id,
	bloz7												as product_bk,
	'products'											as product_source, -- see c_ceec_bch.bch_db.stage::staging_common_lib acres_id
	cast(null as date)									as product_valid_from,
	cast(null as date)									as product_valid_to,
	cast(null as string)							as product_is_valid,
	--cast(null as string)							as product_change_type,
	coalesce(aktualnosc::date, (current_date)) as LastModifiedDate,
	'N'													as PRODUCT_LAD,
	--batch												as product_batch,
	bloz7												as bloz7,
	ean												    as ean,
	sap_id											    as sap_id,
	sku_name											as sku_name,
	sku_short_name							     		as sku_short_name,
	bazyl												as bazyl,
	nr_pozwolenia										as nr_pozwolenia,
	pkwiu												as pkwiu,
	sap_name									 		as sap_name,
	status										    	as status,
	brand_group											as brand_group,
	brand												as brand,
	case Is_Commercial when 'x' then 'Y' else 'N' end	as Is_Commercial,
	case Is_MassMarket when 'x' then 'Y' else 'N' end	as Is_MassMarket,
	case Is_MSL_List when 'x' then 'Y' else 'N' end		as Is_MSL_List,
	case Is_Contracted when 'x' then 'Y' else 'N' end	as Is_Contracted,
	category											as category,
	fct_tool_name										as fct_tool_name,
	product_type										as product_type,
	attribute											as attribute,
	active_substance_dosage								as active_substance_dosage,
	key_words											as key_words,
	form												as form,
	units_volume										as units_volume,
	unit_of_measurement									as unit_of_measurement,
	round(vat::decimal(8,2),2)							as vat,
	exfactory_price										as exfactory_price,
	coalesce(aktualnosc::date, (current_date-1))	as aktualnosc,
  current_timestamp() ETLLastModifiedDate
from (
	select *,row_number() over (partition by bloz7 order by coalesce(aktualnosc::date, (current_date-1)) desc) as rn
	from emea_quality_corr_ceec.wdy_pl_products 
) t where t.RN = 1
)