CREATE TABLE chdaa_prd_lz_emea.emea_curated_disc_bnlx.nl_dim_product (
  ETLIsDeleted BOOLEAN,
  ETLChecksum STRING,
  ETLLastModifiedDate TIMESTAMP,
  product_agg_lvl1_code STRING,
  product_stub_id STRING,
  product_ean_descr STRING,
  product_agg_lvl6_descr STRING,
  product_agg_lvl4_code STRING,
  product_agg_lvl3_code STRING,
  product_agg_lvl2_descr STRING,
  file_name STRING,
  product_level STRING,
  product_agg_lvl6_code STRING,
  load_id STRING,
  product_agg_lvl7_code STRING,
  manufacturer STRING,
  product_agg_lvl8_descr STRING,
  product_agg_lvl2_code STRING,
  product_identifier_code STRING,
  product_agg_lvl5_code STRING,
  product_agg_lvl8_code STRING,
  product_agg_lvl3_descr STRING,
  content STRING,
  product_ean_code STRING,
  product_agg_lvl4_descr STRING,
  product_agg_lvl5_descr STRING,
  d_product_code STRING,
  product_agg_lvl7_descr STRING,
  iri_product_description STRING,
  product_entry_type STRING,
  product_agg_lvl1_descr STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://curated@zpdatacoresadpemea.dfs.core.windows.net/discovery/bnlx/nl_dim_product'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')