CREATE TABLE chdaa_prd_lz_emea.emea_curated_disc_bnlx.dim_material_p_001 (
  ETLIsDeleted BOOLEAN,
  ETLLineageID STRING,
  ETLChecksum STRING,
  ETLLastModifiedDate TIMESTAMP,
  d_pasite STRING,
  dprodh4 STRING,
  dlp_form STRING,
  d_raube STRING,
  d_gtin1 STRING,
  dbrand STRING,
  dprodh2___t STRING,
  d_gtin2u___t STRING,
  d_fgpsu STRING,
  d_uvp STRING,
  d_gtin1c STRING,
  dprodh5 STRING,
  d_gtin2c STRING,
  dprodh5___t STRING,
  d_cpckd STRING,
  dprodh1___t STRING,
  `0extmatlgrp` STRING,
  `0prodh6` STRING,
  d_gtin2u STRING,
  dan_cog STRING,
  dprodh1 STRING,
  `0matl_type___t` STRING,
  `0matl_group` STRING,
  dprodh6 STRING,
  d_gtin1u___t STRING,
  d_raube___t STRING,
  d_cbpck STRING,
  `0material` STRING,
  d_gtin1c___t STRING,
  division___t STRING,
  `0base_uom` STRING,
  dbrand___t STRING,
  `0material___t` STRING,
  `0matl_type` STRING,
  d_fgps STRING,
  dprodh3___t STRING,
  `0base_uom___t` STRING,
  dprodh3 STRING,
  d_gtin2 STRING,
  d_pptyp STRING,
  d_prsite STRING,
  d_trian STRING,
  dprodh2 STRING,
  dprodh6___t STRING,
  `0del_flag` STRING,
  `0material_trim` STRING,
  division STRING,
  dprodh4___t STRING,
  dan_cog___t STRING,
  `0prodh1` STRING,
  dbrandf STRING,
  d_lcpha STRING,
  `0eanupc` STRING,
  d_gtin1u STRING,
  d_gtin2c___t STRING,
  `0prodh6___t` STRING,
  dbrandf___t STRING,
  dlp_form__t STRING)
USING delta
LOCATION 'abfss://curated@zpdatacoresadpemea.dfs.core.windows.net/discovery/bnlx/dim_material_p_001'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')