CREATE TABLE chdaa_prd_lz_emea.emea_curated_disc_bnlx.dim_custsales_p_001 (
  ETLLastModifiedDate TIMESTAMP,
  ETLIsDeleted BOOLEAN,
  ETLLineageID STRING,
  ETLChecksum STRING,
  `0cust_grp5` STRING,
  `0cust_sales_trim_sap` STRING,
  `0cust_group___t` STRING,
  `0price_grp` STRING,
  dcustgrp3___t STRING,
  `0salesorg___t` STRING,
  `0cust_grp1` STRING,
  `0cust_grp2` STRING,
  `0division___t` STRING,
  `0cust_sales_trim` STRING,
  dcustgrp1 STRING,
  dcustgrp1___t STRING,
  `0cust_sales___t` STRING,
  dcustgrp2 STRING,
  `0cust_group` STRING,
  `0distr_chan___t` STRING,
  `0distr_chan` STRING,
  `0cust_sales` STRING,
  dcustgrp4___t STRING,
  dcustgrp5 STRING,
  `0cust_grp4` STRING,
  `0cust_grp3` STRING,
  dcustgrp2___t STRING,
  dcustgrp5___t STRING,
  dctyspcod STRING,
  `0salesorg` STRING,
  dcustgrp4 STRING,
  dctyspcod___t STRING,
  dcustgrp3 STRING,
  `0division` STRING)
USING delta
LOCATION 'abfss://curated@zpdatacoresadpemea.dfs.core.windows.net/discovery/bnlx/dim_custsales_p_001'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')