CREATE TABLE chdaa_prd_lz_emea.emea_curated_disc_bnlx.nl_fact_sales (
  ETLChecksum STRING,
  ETLIsDeleted BOOLEAN,
  ETLLineageID STRING,
  any_promotion_volume FLOAT,
  weighted_distribution_12weeks FLOAT,
  avg_base_price_per_unit FLOAT,
  d_framework_code STRING,
  d_geography_code STRING,
  base_volume FLOAT,
  d_time_period_code STRING,
  any_promotion_units FLOAT,
  file_name STRING,
  sales_eur FLOAT,
  load_id STRING,
  weighted_rate_units_12weeks FLOAT,
  weighted_distribution_weekly FLOAT,
  stores_selling_percentage FLOAT,
  base_eur FLOAT,
  incremental_eur FLOAT,
  base_units FLOAT,
  d_product_code STRING,
  any_promotion_eur FLOAT,
  sales_units FLOAT,
  weighted_rate_eur FLOAT,
  incremental_volume FLOAT,
  avg_base_price_per_volume FLOAT,
  weighted_rate_units FLOAT,
  sales_volume FLOAT,
  d_outlet_code STRING,
  ETLLastModifiedDate TIMESTAMP)
USING delta
LOCATION 'abfss://curated@zpdatacoresadpemea.dfs.core.windows.net/discovery/bnlx/nl_fact_sales'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')