CREATE VIEW emea_raw_src_ceec.vw_m360_ds_um_pt_dim_product (
  id COMMENT 'Id',
  country COMMENT 'Country',
  version COMMENT 'Version',
  data_source COMMENT 'Data Source',
  category_name COMMENT 'Category Name',
  sub_category_name COMMENT 'Sub Category Name',
  segment_name COMMENT 'Segment Name',
  segment_bch COMMENT 'Segment Bch',
  segment_bch_brand COMMENT 'Segment Bch Brand',
  manufacturer_corporation COMMENT 'Manufacturer Corporation',
  manufacturer_local_name COMMENT 'Manufacturer Local Name',
  brand_name COMMENT 'Brand Name',
  brand_local_name COMMENT 'Brand Local Name',
  sub_brand_name COMMENT 'Sub Brand Name',
  product_description COMMENT 'Product Description',
  product_launch_date COMMENT 'Product Launch Date',
  product_type COMMENT 'Product Type',
  product_local_description COMMENT 'Product Local Description',
  pack_launch_date COMMENT 'Pack Launch Date',
  pack_size_value COMMENT 'Pack Size Value',
  pack_size_measure COMMENT 'Pack Size Measure',
  pack_size_group COMMENT 'Pack Size Group',
  pack_form COMMENT 'Pack Form',
  pack_form_extd COMMENT 'Pack Form Extd',
  pack_form_detail COMMENT 'Pack Form Detail',
  pack_description COMMENT 'Pack Description',
  power_brand_flag COMMENT 'Power Brand Flag',
  power_brand_type COMMENT 'Power Brand Type',
  peer_group_flag COMMENT 'Peer Group Flag',
  local_category_name COMMENT 'Local Category Name',
  local_sub_category_name COMMENT 'Local Sub Category Name',
  local_segment_name COMMENT 'Local Segment Name',
  local_form COMMENT 'Local Form',
  local_otc4_description COMMENT 'Local Otc4 Description',
  local_atc4_description COMMENT 'Local Atc4 Description',
  local_product_type COMMENT 'Local Product Type',
  local_product_sub_type COMMENT 'Local Product Sub Type',
  local_key_business_category COMMENT 'Local Key Business Category',
  local_user COMMENT 'Local User',
  local_ingredient COMMENT 'Local Ingredient',
  relevant_market_flag COMMENT 'Relevant Market Flag',
  uov_factor COMMENT 'Global UoV Factor',
  uov_factor_rule COMMENT 'Global UoV Factor Rule',
  is_brand_produced_by_bayer COMMENT 'Is Brand Produced By Bayer',
  rel_m_category COMMENT 'Relative Main Category',
  pack_partition COMMENT 'Pack Partition',
  bayer_flag COMMENT 'Bayer Flag',
  segment_mapped COMMENT 'Segment Mapped',
  comparison_id COMMENT 'Comparison Id',
  brand_by_manufacturer COMMENT 'Brand by Manufacturer',
  pack_size_str COMMENT 'Pack Size',
  local_sku_entity COMMENT 'Local Sku Entity',
  pack_entity COMMENT 'Pack Entity',
  product_entity COMMENT 'Product Entity',
  product_launch_date_eff COMMENT 'Product Launch Date Eff',
  product_launch_date_eff_source COMMENT 'Product Launch Date Eff Source',
  etl_last_load COMMENT 'Etl Last Load',
  global_atc1_description COMMENT 'GLOBAL_ATC1_DESCRIPTION',
  global_atc2_description COMMENT 'GLOBAL_ATC2_DESCRIPTION',
  global_atc3_description COMMENT 'GLOBAL_ATC3_DESCRIPTION',
  global_atc4_description COMMENT 'GLOBAL_ATC4_DESCRIPTION',
  global_otc1_description COMMENT 'GLOBAL_OTC1_DESCRIPTION',
  global_otc2_description COMMENT 'GLOBAL_OTC2_DESCRIPTION',
  global_otc3_description COMMENT 'GLOBAL_OTC3_DESCRIPTION',
  global_otc4_description COMMENT 'GLOBAL_OTC4_DESCRIPTION',
  global_category_alternative COMMENT 'Global Category Alternative',
  global_sub_category_alternative COMMENT 'Global Sub-Category Alternative',
  global_segment_alternative COMMENT 'Global Segment Alternative',
  global_brand_alternative COMMENT 'Global Brand Alternative',
  global_sub_brand_alternative COMMENT 'Global Sub-Brand Alternative',
  global_product_line_alternative COMMENT 'Global Product Line Alternative',
  global_product_type COMMENT 'Global Product Type',
  global_user COMMENT 'Global User',
  global_attribute_placeholder1 COMMENT 'Global Attribute Placeholder 1',
  global_attribute_placeholder2 COMMENT 'Global Attribute Placeholder 2',
  global_attribute_placeholder3 COMMENT 'Global Attribute Placeholder 3',
  global_attribute_placeholder4 COMMENT 'Global Attribute Placeholder 4')
WITH SCHEMA BINDING
AS (
  SELECT 
  `ID` AS id,
`COUNTRY` AS country,
`VERSION` AS version,
`DATA_SOURCE` AS data_source,
`CATEGORY.NAME` AS category_name,
`SUB_CATEGORY.NAME` AS sub_category_name,
`SEGMENT.NAME` AS segment_name,
`SEGMENT.BCH` AS segment_bch,
`SEGMENT.BCH_BRAND` AS segment_bch_brand,
`MANUFACTURER.CORPORATION` AS manufacturer_corporation,
`MANUFACTURER.LOCAL.NAME` AS manufacturer_local_name,
`BRAND.NAME` AS brand_name,
`BRAND.LOCAL.NAME` AS brand_local_name,
`SUB_BRAND.NAME` AS sub_brand_name,
`PRODUCT.DESCRIPTION` AS product_description,
`PRODUCT.LAUNCH.DATE` AS product_launch_date,
`PRODUCT.TYPE` AS product_type,
`PRODUCT.LOCAL.DESCRIPTION` AS product_local_description,
`PACK.LAUNCH.DATE` AS pack_launch_date,
`PACK.SIZE.VALUE` AS pack_size_value,
`PACK.SIZE.MEASURE` AS pack_size_measure,
`PACK.SIZE.GROUP` AS pack_size_group,
`PACK.FORM` AS pack_form,
`PACK.FORM_EXTD` AS pack_form_extd,
`PACK.FORM_DETAIL` AS pack_form_detail,
`PACK.DESCRIPTION` AS pack_description,
`POWER_BRAND_FLAG` AS power_brand_flag,
`POWER_BRAND_TYPE` AS power_brand_type,
`PEER_GROUP_FLAG` AS peer_group_flag,
`LOCAL.CATEGORY.NAME` AS local_category_name,
`LOCAL.SUB_CATEGORY.NAME` AS local_sub_category_name,
`LOCAL.SEGMENT.NAME` AS local_segment_name,
`LOCAL.FORM` AS local_form,
`LOCAL.OTC4.DESCRIPTION` AS local_otc4_description,
`LOCAL.ATC4.DESCRIPTION` AS local_atc4_description,
`LOCAL.PRODUCT.TYPE` AS local_product_type,
`LOCAL.PRODUCT.SUB_TYPE` AS local_product_sub_type,
`LOCAL.KEY_BUSINESS_CATEGORY` AS local_key_business_category,
`LOCAL.USER` AS local_user,
`LOCAL.INGREDIENT` AS local_ingredient,
`RELEVANT_MARKET_FLAG` AS relevant_market_flag,
`UOV_FACTOR` AS uov_factor,
`UOV_FACTOR_RULE` AS uov_factor_rule,
`IS_BRAND_PRODUCED_BY_BAYER` AS is_brand_produced_by_bayer,
`REL_M_CATEGORY` AS rel_m_category,
`PACK_PARTITION` AS pack_partition,
`BAYER_FLAG` AS bayer_flag,
`SEGMENT_MAPPED` AS segment_mapped,
`COMPARISON_ID` AS comparison_id,
`BRAND_BY_MANUFACTURER` AS brand_by_manufacturer,
`PACK_SIZE_STR` AS pack_size_str,
`LOCAL_SKU_ENTITY` AS local_sku_entity,
`PACK_ENTITY` AS pack_entity,
`PRODUCT_ENTITY` AS product_entity,
`PRODUCT_LAUNCH_DATE_EFF` AS product_launch_date_eff,
`PRODUCT_LAUNCH_DATE_EFF_SOURCE` AS product_launch_date_eff_source,
`ETL_Last_Load` AS etl_last_load,
`GLOBAL_ATC1_DESCRIPTION` AS global_atc1_description,
`GLOBAL_ATC2_DESCRIPTION` AS global_atc2_description,
`GLOBAL_ATC3_DESCRIPTION` AS global_atc3_description,
`GLOBAL_ATC4_DESCRIPTION` AS global_atc4_description,
`GLOBAL_OTC1_DESCRIPTION` AS global_otc1_description,
`GLOBAL_OTC2_DESCRIPTION` AS global_otc2_description,
`GLOBAL_OTC3_DESCRIPTION` AS global_otc3_description,
`GLOBAL_OTC4_DESCRIPTION` AS global_otc4_description,
`GLOBAL_CATEGORY_ALTERNATIVE` AS global_category_alternative,
`GLOBAL_SUB_CATEGORY_ALTERNATIVE` AS global_sub_category_alternative,
`GLOBAL_SEGMENT_ALTERNATIVE` AS global_segment_alternative,
`GLOBAL_BRAND_ALTERNATIVE` AS global_brand_alternative,
`GLOBAL_SUB_BRAND_ALTERNATIVE` AS global_sub_brand_alternative,
`GLOBAL_PRODUCT_LINE_ALTERNATIVE` AS global_product_line_alternative,
`GLOBAL_PRODUCT_TYPE` AS global_product_type,
`GLOBAL_USER` AS global_user,
`GLOBAL_ATTRIBUTE_PLACEHOLDER1` AS global_attribute_placeholder1,
`GLOBAL_ATTRIBUTE_PLACEHOLDER2` AS global_attribute_placeholder2,
`GLOBAL_ATTRIBUTE_PLACEHOLDER3` AS global_attribute_placeholder3,
`GLOBAL_ATTRIBUTE_PLACEHOLDER4` AS global_attribute_placeholder4
   FROM chdaa_prd_cda_mkt.mkt_curated_prov.leg_m360_ds_um_pt_dim_product
)