CREATE VIEW emea_consume_bnlx.dim_man_ch_customer_mapping_sql (
  ETLLastModifiedDate,
  employee_cwid,
  sap_customer_country,
  sap_customer_zip_code,
  cluster,
  employee_name,
  update_by,
  sap_customer_city,
  d_customer_mapping_code,
  main_sap_customer_code,
  extract_by,
  sap_customer_code,
  status,
  sap_customer_name,
  country_code,
  sap_apb_code,
  update_date,
  organization,
  channel,
  extract_date,
  dummy,
  ETLLineageID,
  ETLIsDeleted,
  ETLChecksum)
WITH SCHEMA BINDING
AS (
SELECT   ETLLastModifiedDate,
  employee_cwid,
  sap_customer_country,
  sap_customer_zip_code,
  cluster,
  employee_name,
  update_by,
  sap_customer_city,
  d_customer_mapping_code,
  main_sap_customer_code,
  extract_by,
  sap_customer_code,
  status,
  sap_customer_name,
  country_code,
  sap_apb_code,
  update_date,
  organization,
  channel,
  extract_date,
  dummy,
  ETLLineageID,
  ETLIsDeleted,
  ETLChecksum FROM emea_curated_disc_bnlx.dim_man_ch_customer_mapping_sql)