CREATE VIEW emea_consume_bnlx.nl_dim_product (
  ETLIsDeleted,
  ETLChecksum,
  ETLLastModifiedDate,
  product_agg_lvl1_code,
  product_stub_id,
  product_ean_descr,
  product_agg_lvl6_descr,
  product_agg_lvl4_code,
  product_agg_lvl3_code,
  product_agg_lvl2_descr,
  file_name,
  product_level,
  product_agg_lvl6_code,
  load_id,
  product_agg_lvl7_code,
  manufacturer,
  product_agg_lvl8_descr,
  product_agg_lvl2_code,
  product_identifier_code,
  product_agg_lvl5_code,
  product_agg_lvl8_code,
  product_agg_lvl3_descr,
  content,
  product_ean_code,
  product_agg_lvl4_descr,
  product_agg_lvl5_descr,
  d_product_code,
  product_agg_lvl7_descr,
  iri_product_description,
  product_entry_type,
  product_agg_lvl1_descr,
  ETLLineageID)
WITH SCHEMA BINDING
AS (
SELECT * FROM chdaa_prd_lz_emea.emea_curated_disc_bnlx.nl_dim_product)