CREATE VIEW emea_consume_bnlx.nl_fact_sales (
  ETLChecksum,
  ETLIsDeleted,
  ETLLineageID,
  any_promotion_volume,
  weighted_distribution_12weeks,
  avg_base_price_per_unit,
  d_framework_code,
  d_geography_code,
  base_volume,
  d_time_period_code,
  any_promotion_units,
  file_name,
  sales_eur,
  load_id,
  weighted_rate_units_12weeks,
  weighted_distribution_weekly,
  stores_selling_percentage,
  base_eur,
  incremental_eur,
  base_units,
  d_product_code,
  any_promotion_eur,
  sales_units,
  weighted_rate_eur,
  incremental_volume,
  avg_base_price_per_volume,
  weighted_rate_units,
  sales_volume,
  d_outlet_code,
  ETLLastModifiedDate)
WITH SCHEMA BINDING
AS (
SELECT * FROM chdaa_prd_lz_emea.emea_curated_disc_bnlx.nl_fact_sales)