CREATE TABLE chdaa_prd_lz_emea.emea_quality_corr_bnlx.fico_dim_customer (
  ETLIsDeleted BOOLEAN,
  ETLLineageID STRING,
  ETLChecksum STRING,
  cust_lead STRING,
  cust_lead_id STRING,
  cust_postal_code STRING,
  optime STRING,
  cust_class_id STRING,
  cust_ch_01 STRING,
  cust_duns STRING,
  cust_ch_id_02 STRING,
  cust_accnt_grp_id STRING,
  cust_sort STRING,
  cust_country STRING,
  cust STRING,
  cust_region STRING,
  cust_region_id STRING,
  cust_accnt_grp STRING,
  cust_ch_id_01 STRING,
  cust_sid STRING,
  cust_class STRING,
  cust_duns_id STRING,
  cust_industry_id STRING,
  opsys STRING,
  cust_city STRING,
  cust_id STRING,
  cust_street STRING,
  cust_ch_02 STRING,
  cust_industry STRING,
  optype STRING,
  ETLLastModifiedDate TIMESTAMP)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/correction/bnlx/fico_dim_customer'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')