CREATE TABLE chdaa_prd_lz_emea.emea_quality_corr_bnlx.fico_dim_sales_customer (
  ETLChecksum STRING,
  ETLLastModifiedDate TIMESTAMP,
  cust_grp_hl_03 STRING,
  sales_cust_sid STRING,
  distr_chan_id STRING,
  cust_grp STRING,
  sales_org STRING,
  optime STRING,
  price_group STRING,
  cust_grp_hl_id_03 STRING,
  cust_grp_hl_02 STRING,
  division_id STRING,
  sales_org_id STRING,
  cust_grp_hl_04 STRING,
  cust_grp_hl_id_04 STRING,
  sales_cust_id STRING,
  cust_grp_hl_05 STRING,
  cust_country_code STRING,
  cust_grp_id STRING,
  cust_grp_hl_01 STRING,
  price_group_id STRING,
  opsys STRING,
  cust_grp_hl_id_05 STRING,
  sales_cust STRING,
  division STRING,
  cust_grp_hl_id_01 STRING,
  cust_grp_hl_id_02 STRING,
  distr_chain STRING,
  cust_country_code_id STRING,
  optype STRING,
  ETLLineageID STRING,
  ETLIsDeleted BOOLEAN)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/correction/bnlx/fico_dim_sales_customer'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')