CREATE TABLE chdaa_prd_lz_emea.emea_quality_corr_bnlx.fico_dim_business_responsibility (
  ETLLastModifiedDate TIMESTAMP,
  ETLIsDeleted BOOLEAN,
  ETLLineageID STRING,
  cat_ch STRING,
  bsv_hl_09 STRING,
  bsv_hl_10 STRING,
  company_code_id STRING,
  plant_id STRING,
  msrc_id STRING,
  distr_chan_id STRING,
  bsv_hl_id_07 STRING,
  bsv STRING,
  bsv_hl_id_09 STRING,
  cs_item_sub_cat_id STRING,
  optime STRING,
  sg_cv_id STRING,
  pc_cv STRING,
  sbe_cv STRING,
  bsv_hl_id_06 STRING,
  ru_cv STRING,
  country_fd_id STRING,
  cs_item_id STRING,
  respo_hl_id_02 STRING,
  msrc STRING,
  respo_hl_id_01 STRING,
  bsv_hl_id_04 STRING,
  bg_cv_id STRING,
  respo_hl_02 STRING,
  loc_bu_id STRING,
  sales_org_id STRING,
  bsv_hl_id_10 STRING,
  bsv_hl_08 STRING,
  ps_respo_sid STRING,
  cs_chart_id STRING,
  pc_id STRING,
  respo_hl_01 STRING,
  ps_site STRING,
  material_id STRING,
  send_cctr_id STRING,
  cat_ch_id STRING,
  ru_cv_id STRING,
  cs_item_sub_id STRING,
  respo_sid STRING,
  bsv_hl_05 STRING,
  bsv_hl_03 STRING,
  bsv_hl_02 STRING,
  bsv_hl_id_05 STRING,
  bsv_hl_06 STRING,
  opsys STRING,
  loc_bu STRING,
  ps_site_id STRING,
  bsv_hl_04 STRING,
  pc_cv_id STRING,
  bsv_hl_id_08 STRING,
  bsv_hl_01 STRING,
  bsv_hl_id_01 STRING,
  bsv_hl_07 STRING,
  bsv_hl_id_02 STRING,
  bsv_hl_id_03 STRING,
  respo_id STRING,
  bsv_id STRING,
  co_area_id STRING,
  sbe_cv_id STRING,
  bg_cv STRING,
  optype STRING,
  sg_cv STRING,
  ETLChecksum STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/correction/bnlx/fico_dim_business_responsibility'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')