CREATE TABLE chdaa_prd_lz_emea.emea_quality_corr_bnlx.fico_dim_sold_to (
  ETLChecksum STRING,
  ETLIsDeleted BOOLEAN,
  sold_to_country_id STRING,
  sold_to_ch_id_01 STRING,
  optime STRING,
  sold_to_ch_id_02 STRING,
  sold_to_accnt_grp_id STRING,
  sold_to_region STRING,
  sold_to_city STRING,
  sold_to_class_id STRING,
  sold_to_industry STRING,
  sold_to_ch_01 STRING,
  sold_to_ch_02 STRING,
  sold_to_country STRING,
  sold_to_sid STRING,
  sold_to_industry_id STRING,
  sold_to_region_id STRING,
  opsys STRING,
  sold_to_street STRING,
  sold_to_postal_code STRING,
  sold_to_class STRING,
  sold_to STRING,
  sold_to_accnt_grp STRING,
  sold_to_id STRING,
  optype STRING,
  ETLLineageID STRING,
  ETLLastModifiedDate TIMESTAMP)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/correction/bnlx/fico_dim_sold_to'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')