CREATE TABLE chdaa_prd_lz_emea.emea_quality_int_ceec.fact_farmaprom_orderlineprocessing (
  id_zamowienia BIGINT,
  pakiet_od TIMESTAMP,
  numer_zamowienia STRING,
  data_zamowienia TIMESTAMP,
  uwagiwewnetrzne STRING,
  id_przypisanie_statusu_produktu_do_zamowienia BIGINT,
  uwagiodprzedstawicielahurtowni STRING,
  id_produktu BIGINT,
  data_wysylki_do_hurtowni TIMESTAMP,
  pakiet STRING,
  orderlpr_lad STRING,
  nazwa_hurtowni STRING,
  dodatkowa_informacja STRING,
  liczba BIGINT,
  LastModifiedDate DATE,
  rabat FLOAT,
  orderlpr_batch INT,
  bloz7 STRING,
  id_przypisanie_produktu_do_zamowienia BIGINT,
  status_produktu_w_zamowieniu STRING,
  orderlpr_source STRING,
  pakiet_do TIMESTAMP,
  siec_firmowa_nazwa STRING,
  orderlpr_bk BIGINT,
  id_apteki BIGINT,
  uwaga_do_produktu STRING,
  id_zamowienia_sieciowego BIGINT,
  id_kamsoft STRING,
  uwagiodhurtowni STRING,
  orderlpr_id STRING,
  orderlpr_is_valid BOOLEAN,
  orderlpr_valid_from TIMESTAMP,
  orderlpr_valid_to TIMESTAMP,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksumSCD1 STRING,
  ETLChecksumSCD2 STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/integration/ceec/fact_farmaprom_orderlineprocessing'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')