CREATE TABLE chdaa_prd_lz_emea.emea_quality_int_ceec.dim_customers (
  customer_id STRING,
  customer_valid_from TIMESTAMP,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksumSCD2 STRING,
  iqvia_brick STRING,
  position STRING,
  chain_type STRING,
  kamsoft_agreement STRING,
  group_type STRING,
  id_customer STRING,
  id_farmaprom INT,
  Rep_email_Commercial STRING,
  behind_glass_exposition STRING,
  rep_id_education STRING,
  behind_counter_exposition STRING,
  id_esalesweb STRING,
  city STRING,
  nip STRING,
  dnv_education STRING,
  zip_code STRING,
  area_commercial STRING,
  customer_change_type STRING,
  pharmacy_name STRING,
  area_education STRING,
  customer_lad STRING,
  id_acres INT,
  pharmacy_type STRING,
  chain_customer_account STRING,
  LastModifiedDate DATE,
  id_external_reporting INT,
  name_chain_customer STRING,
  importance STRING,
  group_owner STRING,
  commercial_segment STRING,
  rep_name_education STRING,
  customer_bk BIGINT,
  adress STRING,
  education_segment STRING,
  external_source STRING,
  attributes STRING,
  id_chain_customer INT,
  email STRING,
  customer_group STRING,
  contract STRING,
  dnv_commercial STRING,
  pharmacy_status STRING,
  rep_id_commercial STRING,
  is_dermatological STRING,
  is_self_service STRING,
  Rep_email_Commercial_2 STRING,
  is_kamsoft STRING,
  last_visit_commercial DATE,
  phone_number STRING,
  store_window STRING,
  customer_change_timestamp TIMESTAMP,
  rep_name_commercial STRING,
  is_ordering STRING,
  customer_source STRING,
  last_visit_education DATE,
  customer_is_valid BOOLEAN,
  customer_valid_to TIMESTAMP,
  ETLChecksumSCD1 STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/integration/ceec/dim_customers'
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')