CREATE TABLE chdaa_prd_lz_emea.emea_quality_int_ceec.dim_products (
  product_id STRING,
  product_valid_from TIMESTAMP,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksumSCD2 STRING,
  nr_pozwolenia STRING,
  sku_name STRING,
  form STRING,
  sku_short_name STRING,
  vat DECIMAL(8,2),
  bloz7 INT,
  bazyl INT,
  status STRING,
  is_msl_list STRING,
  product_type STRING,
  brand_group STRING,
  exfactory_price DECIMAL(8,2),
  is_massmarket STRING,
  LastModifiedDate DATE,
  is_commercial STRING,
  key_words STRING,
  aktualnosc DATE,
  product_bk STRING,
  brand STRING,
  product_source STRING,
  ean BIGINT,
  fct_tool_name STRING,
  is_contracted STRING,
  sap_id INT,
  active_substance_dosage STRING,
  pkwiu STRING,
  sap_name STRING,
  attribute STRING,
  unit_of_measurement STRING,
  category STRING,
  units_volume STRING,
  product_is_valid BOOLEAN,
  product_valid_to TIMESTAMP,
  ETLChecksumSCD1 STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/integration/ceec/dim_products'
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')