CREATE VIEW emea_raw_src_ceec.vw_m360_ds_um_pt_fact (
  time_id,
  country,
  currency,
  product_id,
  distribution_id,
  agg_type,
  version,
  sales_unit,
  sales_volume,
  sales_value_msp,
  sales_value_pub,
  sales_value_trd,
  sales_ya_unit,
  sales_ya_volume,
  sales_ya_value_msp,
  sales_ya_value_pub,
  sales_ya_value_trd,
  sales_2ya_unit,
  sales_2ya_volume,
  sales_2ya_value_msp,
  sales_2ya_value_pub,
  sales_2ya_value_trd,
  distr_sales_numeric,
  distr_sales_weighted,
  distr_ya_sales_numeric,
  distr_ya_sales_weighted,
  distr_2ya_sales_numeric,
  distr_2ya_sales_weighted,
  rel_market_sum_sales_value_pub_eur,
  rel_market_sum_sales_ya_value_pub_eur,
  rel_market_sum_sales_unit,
  rel_market_sum_sales_ya_unit,
  is_forecast,
  sales_value_msp_eur,
  sales_value_pub_eur,
  sales_value_trd_eur,
  sales_ya_value_msp_eur,
  sales_ya_value_pub_eur,
  sales_ya_value_trd_eur,
  sales_2ya_value_msp_eur,
  sales_2ya_value_pub_eur,
  sales_2ya_value_trd_eur,
  data_source,
  fact_type,
  is_local_sku_wsales,
  outliers_flag_int,
  growth_drivers,
  year,
  period_display_name,
  date_start_year_agg_type,
  date_start_mon_year_agg_type,
  growth_drivers_grouped,
  base_units_change,
  base_price_change,
  intersection_effect,
  new_pack_change,
  new_product_change,
  etl_last_load)
WITH SCHEMA BINDING
AS (
  SELECT 
  `TIME.ID` AS time_id,
`COUNTRY` AS country,
`CURRENCY` AS currency,
`PRODUCT.ID` AS product_id,
`DISTRIBUTION.ID` AS distribution_id,
`AGG_TYPE` AS agg_type,
`VERSION` AS version,
`SALES.UNIT` AS sales_unit,
`SALES.VOLUME` AS sales_volume,
`SALES.VALUE.MSP` AS sales_value_msp,
`SALES.VALUE.PUB` AS sales_value_pub,
`SALES.VALUE.TRD` AS sales_value_trd,
`SALES_YA.UNIT` AS sales_ya_unit,
`SALES_YA.VOLUME` AS sales_ya_volume,
`SALES_YA.VALUE.MSP` AS sales_ya_value_msp,
`SALES_YA.VALUE.PUB` AS sales_ya_value_pub,
`SALES_YA.VALUE.TRD` AS sales_ya_value_trd,
`SALES_2YA.UNIT` AS sales_2ya_unit,
`SALES_2YA.VOLUME` AS sales_2ya_volume,
`SALES_2YA.VALUE.MSP` AS sales_2ya_value_msp,
`SALES_2YA.VALUE.PUB` AS sales_2ya_value_pub,
`SALES_2YA.VALUE.TRD` AS sales_2ya_value_trd,
`DISTR.SALES.NUMERIC` AS distr_sales_numeric,
`DISTR.SALES.WEIGHTED` AS distr_sales_weighted,
`DISTR_YA.SALES.NUMERIC` AS distr_ya_sales_numeric,
`DISTR_YA.SALES.WEIGHTED` AS distr_ya_sales_weighted,
`DISTR_2YA.SALES.NUMERIC` AS distr_2ya_sales_numeric,
`DISTR_2YA.SALES.WEIGHTED` AS distr_2ya_sales_weighted,
`REL_MARKET_SUM.SALES_VALUE_PUB_EUR` AS rel_market_sum_sales_value_pub_eur,
`REL_MARKET_SUM.SALES_YA_VALUE_PUB_EUR` AS rel_market_sum_sales_ya_value_pub_eur,
`REL_MARKET_SUM.SALES_UNIT` AS rel_market_sum_sales_unit,
`REL_MARKET_SUM.SALES_YA_UNIT` AS rel_market_sum_sales_ya_unit,
`IS_FORECAST` AS is_forecast,
`SALES.VALUE.MSP_EUR` AS sales_value_msp_eur,
`SALES.VALUE.PUB_EUR` AS sales_value_pub_eur,
`SALES.VALUE.TRD_EUR` AS sales_value_trd_eur,
`SALES_YA.VALUE.MSP_EUR` AS sales_ya_value_msp_eur,
`SALES_YA.VALUE.PUB_EUR` AS sales_ya_value_pub_eur,
`SALES_YA.VALUE.TRD_EUR` AS sales_ya_value_trd_eur,
`SALES_2YA.VALUE.MSP_EUR` AS sales_2ya_value_msp_eur,
`SALES_2YA.VALUE.PUB_EUR` AS sales_2ya_value_pub_eur,
`SALES_2YA.VALUE.TRD_EUR` AS sales_2ya_value_trd_eur,
`DATA_SOURCE` AS data_source,
`FACT_TYPE` AS fact_type,
`IS_LOCAL_SKU_WSALES` AS is_local_sku_wsales,
`OUTLIERS_FLAG_INT` AS outliers_flag_int,
`GROWTH_DRIVERS` AS growth_drivers,
`YEAR` AS year,
`PERIOD_DISPLAY_NAME` AS period_display_name,
`DATE_START_YEAR_AGG_TYPE` AS date_start_year_agg_type,
`DATE_START_MON_YEAR_AGG_TYPE` AS date_start_mon_year_agg_type,
`GROWTH_DRIVERS_GROUPED` AS growth_drivers_grouped,
`BASE_UNITS_CHANGE` AS base_units_change,
`BASE_PRICE_CHANGE` AS base_price_change,
`INTERSECTION_EFFECT` AS intersection_effect,
`NEW_PACK_CHANGE` AS new_pack_change,
`NEW_PRODUCT_CHANGE` AS new_product_change,
`ETL_Last_Load` AS etl_last_load
   FROM chdaa_prd_cda_mkt.mkt_curated_prov.leg_m360_ds_um_pt_fact
)