CREATE TABLE chdaa_prd_lz_emea.emea_raw_lnd_bnlx.fico_dim_business_responsibility (
  RESPO_SID BIGINT,
  COMPANY_CODE_ID VARCHAR(4) COMMENT 'Company Code ID',
  CO_AREA_ID VARCHAR(4) COMMENT 'Controlling Area ID',
  CS_CHART_ID VARCHAR(2) COMMENT 'Consolidation Chart of Accounts ID',
  CS_ITEM_ID VARCHAR(10) COMMENT 'Item ID',
  CS_ITEM_SUB_ID VARCHAR(10) COMMENT 'Item Subitem ID',
  CS_ITEM_SUB_CAT_ID VARCHAR(3) COMMENT 'Item Subitem Category ID',
  DISTR_CHAN_ID VARCHAR(2) COMMENT 'Distribution Channel ID',
  MATERIAL_ID VARCHAR(18) COMMENT 'Material ID',
  PLANT_ID VARCHAR(4) COMMENT 'Plant ID',
  SALES_ORG_ID VARCHAR(4) COMMENT 'Sales Organization ID',
  SEND_CCTR_ID VARCHAR(10) COMMENT 'Sending Cost Center ID',
  COUNTRY_FD_ID VARCHAR(3) COMMENT 'Country of Final Destination ID',
  PC_ID VARCHAR(10) COMMENT 'Profit Center (Global View), posted ID',
  RESPO_ID VARCHAR(1) COMMENT 'Business Responsibility ID',
  RESPO_HL_ID_01 VARCHAR(18) COMMENT 'Business Responsibility Level ID 1',
  RESPO_HL_ID_02 VARCHAR(18) COMMENT 'Business Responsibility Level ID 2',
  RESPO_HL_01 VARCHAR(40) COMMENT 'Business Responsibility Level 1',
  RESPO_HL_02 VARCHAR(40) COMMENT 'Business Responsibility Level 2',
  BSV_HL_ID_01 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 01',
  BSV_HL_ID_02 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 02',
  BSV_HL_ID_03 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 03',
  BSV_HL_ID_04 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 04',
  BSV_HL_ID_05 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 05',
  BSV_HL_ID_06 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 06',
  BSV_HL_ID_07 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 07',
  BSV_HL_ID_08 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 08',
  BSV_HL_ID_09 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 09',
  BSV_HL_ID_10 VARCHAR(32) COMMENT 'Business Steering View Hierarchy Level ID 10',
  BSV_HL_01 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 01',
  BSV_HL_02 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 02',
  BSV_HL_03 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 03',
  BSV_HL_04 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 04',
  BSV_HL_05 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 05',
  BSV_HL_06 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 06',
  BSV_HL_07 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 07',
  BSV_HL_08 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 08',
  BSV_HL_09 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 09',
  BSV_HL_10 VARCHAR(60) COMMENT 'Business Steering View Hierarchy Level 10',
  BG_CV_ID VARCHAR(2) COMMENT 'Business Group ID',
  BG_CV VARCHAR(40) COMMENT 'Business Group',
  SG_CV_ID VARCHAR(2) COMMENT 'Sub Group ID',
  SG_CV VARCHAR(40) COMMENT 'Sub Group',
  SBE_CV_ID VARCHAR(4) COMMENT 'Strategic Business Entity ID',
  SBE_CV VARCHAR(40) COMMENT 'Strategic Business Entity',
  RU_CV_ID VARCHAR(5) COMMENT 'Reporting Unit ID',
  RU_CV VARCHAR(40) COMMENT 'Reporting Unit',
  PC_CV_ID VARCHAR(10) COMMENT 'Profit Center (Controlling View) ID',
  PC_CV VARCHAR(40) COMMENT 'Profit Center (Controlling View)',
  CAT_CH_ID VARCHAR(4) COMMENT 'Category ID',
  CAT_CH VARCHAR(60) COMMENT 'Category',
  MSRC_ID VARCHAR(3) COMMENT 'Merger Source ID',
  MSRC VARCHAR(40) COMMENT 'Merger Source',
  BSV_ID VARCHAR(250) COMMENT 'Business Steering View ID',
  BSV VARCHAR(40) COMMENT 'Business Steering View',
  LOC_BU_ID VARCHAR(5) COMMENT 'Local Business Unit ID',
  LOC_BU VARCHAR(40) COMMENT 'Local Business Unit',
  PS_RESPO_SID BIGINT,
  PS_SITE_ID VARCHAR(6) COMMENT 'Production Site ID',
  PS_SITE VARCHAR(60) COMMENT 'Production Site',
  BRAND_ID VARCHAR(18) COMMENT 'Brand ID',
  BRAND VARCHAR(40) COMMENT 'Brand',
  BRAND_GROUPING_ID VARCHAR(18) COMMENT 'Brand Grouping ID',
  BRAND_GROUPING VARCHAR(60) COMMENT 'BRAND_GROUPING',
  SUB_BRAND_ID VARCHAR(18) COMMENT 'Sub Brand / Brand Family ID',
  SUB_BRAND VARCHAR(40) COMMENT 'Sub Brand / Brand Family',
  OPSYS VARCHAR(10) COMMENT 'OPSYS',
  OPTIME VARCHAR(25) COMMENT 'OPTIME',
  OPTYPE VARCHAR(1) COMMENT 'OPTYPE',
  ETLLastModifiedDate DATE)
USING delta
LOCATION 'abfss://raw@zpdatacoresadpemea.dfs.core.windows.net/landing/bnlx/fico_dim_business_responsibility'
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')