CREATE TABLE chdaa_prd_lz_emea.emea_raw_lnd_bnlx.fico_fact_sd_order (
  SO_DOC_TYPE_SID BIGINT,
  CO_AREA_SID BIGINT,
  COST_CENTER_SID BIGINT,
  SALES_ORG_SID BIGINT,
  BILL_STATUS_DELIVERY_SID STRING,
  STATUS_SALES_FLOW_SID BIGINT,
  SO_DOC_ITEM_CATEG_SID BIGINT,
  SO_QUOT_REJECT_REASON_SID BIGINT,
  SO_DOC_CATEG_SID BIGINT,
  COUNTRY_FD_SID BIGINT,
  COUNTRY_SID BIGINT,
  COMPANY_CODE_SID BIGINT,
  CUST_ORDER_TYPE_SID BIGINT,
  BILL_TO_SID BIGINT,
  PAYER_SID BIGINT,
  SOLD_TO_SID BIGINT,
  SHIP_TO_SID BIGINT,
  MATERIAL_SID BIGINT,
  PLANT_SID BIGINT,
  TRANSACTION_CODE_SID STRING,
  PC_SID STRING,
  PARTNER_COMPANY_CODE_SID STRING,
  FISCPER_SID BIGINT,
  RLS_AUTH_SID BIGINT,
  CURRENCY_LOCAL_ID VARCHAR(3) COMMENT 'Company Code Currency',
  CURRENCY_GLOBAL_ID STRING,
  NET_VALUE_LC DECIMAL(35,2) COMMENT 'Sales Order Net Value in Local Currency',
  NET_VALUE_GC DECIMAL(35,2) COMMENT 'Sales Order Net Value in Global Currency',
  SO_DOC_ID VARCHAR(10) COMMENT 'Sales Order Document ID',
  SO_DOC_CATEG_ID STRING,
  SO_DOC_REF_ID STRING,
  SO_DOC_REF_CATEG_ID STRING,
  REF_DOC_ID VARCHAR(16) COMMENT 'Reference Document ID',
  SO_DOC_ITEM VARCHAR(6) COMMENT 'Sales Order Document Item',
  SO_DOC_ITEM_REF STRING,
  SCHEDULE_LINE_ID STRING,
  SOURCE_SYSTEM_ID VARCHAR(2) COMMENT 'Source System ID',
  INVOICE_GROSS_VALUE_DC DECIMAL(20,2) COMMENT 'Invoice Gross Value in Document Currency',
  INVOICE_GROSS_VALUE_LC DECIMAL(35,2) COMMENT 'Invoice Gross Value in Local Currency',
  INVOICE_DISCOUNTS_DC DECIMAL(20,2) COMMENT 'Invoice Discounts in Document Currency',
  INVOICE_DISCOUNTS_LC DECIMAL(35,2) COMMENT 'Invoice Discounts in Local Currency',
  INVOICE_SURCHARGE_DC DECIMAL(20,2) COMMENT 'Invoice Surcharge in Document Currency',
  INVOICE_SURCHARGE_LC DECIMAL(35,2) COMMENT 'Invoice Surcharge in Local Currency',
  INVOICE_REBATES_DC DECIMAL(20,2) COMMENT 'Invoice Rebates in Document Currency',
  INVOICE_REBATES_LC DECIMAL(35,2) COMMENT 'Invoice Rebates in Local Currency',
  INVOICE_FREIGHT_COSTS_DC DECIMAL(20,2) COMMENT 'Invoice Freight Costs in Document Currency',
  INVOICE_FREIGHT_COSTS_LC DECIMAL(35,2) COMMENT 'Invoice Freight Costs in Local Currency',
  AMOUNT DECIMAL(35,2) COMMENT 'Amount',
  NET_PRICE DECIMAL(16,2) COMMENT 'Net Price',
  PLAN_GI_DATE_CONF STRING,
  LAST_ACT_GI_DATE STRING,
  REQ_DELIV_DATE DATE COMMENT 'Requested Delivery Date',
  SO_DOC_CHANGE_DATE DATE COMMENT 'Sales Order Last Change Date',
  SO_DOC_ITEM_LAST_CHANGE_DATE DATE COMMENT 'Sales Order Last Change Date of any Item',
  SO_DOC_CREATION_DATE DATE COMMENT 'Sales Order Creation Date',
  GI_DATE STRING,
  SO_DOC_DATE DATE COMMENT 'Sales Order Document Date',
  ACT_GI_DATE STRING,
  DIVESTMENT_SCENARIO_ID STRING,
  PLANNED_BILL_DATE DATE COMMENT 'Planned Billing Date',
  VOL_REBATE_GROUP_ID VARCHAR(2) COMMENT 'Volume Rebate Group ID',
  DELIV_COMPL_FLAG VARCHAR(1) COMMENT 'Delivery Completed Flag',
  SHIP_POINT_ID STRING,
  NAME_OF_ORDERER VARCHAR(40) COMMENT 'Name of Orderer',
  SHIP_COND_ID VARCHAR(2) COMMENT 'Shipping Conditions ID',
  SO_DOC_ITEM_CONF_STATUS_ID VARCHAR(2) COMMENT 'Sales Order Item Confirmation Status ID',
  ORIG_DELIV_STATUS_ITEM_ID VARCHAR(1) COMMENT 'Original Delivery Status of Item ID',
  PLAN_GI_DATE_REQ STRING,
  REL_DATE DATE COMMENT 'Release Date',
  CONF_DELIV_DATE STRING,
  ORIG_REQ_DATE STRING,
  DELIV_DATE_SCHEDULE_LINE STRING,
  CURRENCY_ID STRING,
  CURRENCY_TYPE_ID STRING,
  CURRENCY_DOC_ID STRING,
  SO_NET_WT STRING,
  TAX_VALUE DECIMAL(20,2) COMMENT 'Tax Value',
  SO_TAX_VALUE_LC DECIMAL(35,2) COMMENT 'Sales Order Tax Value in Local Currency',
  SO_NO_OF_ITEMS INT COMMENT 'Number of Order Items',
  VOLUME DECIMAL(19,3) COMMENT 'Volume',
  NET_VALUE_DC DECIMAL(21,2) COMMENT 'Sales Order Net Value in Document Currency',
  SO_CONF_VALUE_LC DECIMAL(35,2) COMMENT 'Sales Order Confirmed Value in Local Currency',
  SO_CONF_VALUE_DC DECIMAL(35,2) COMMENT 'Sales Order Confirmed Value in Document Currency',
  QUANTITY_BU DECIMAL(28,2) COMMENT 'Quantity in Base Unit',
  SO_CONF_QTY_SU DECIMAL(21,3) COMMENT 'Confirmed Quantity in Sales Unit',
  SO_CONF_QTY_BU DECIMAL(21,3) COMMENT 'Confirmed Quantity in Base Unit',
  SO_QUANTITY_SU DECIMAL(21,3) COMMENT 'Quantity in Sales Unit',
  TARGET_QTY_SU DECIMAL(19,3) COMMENT 'Target Quantity in Sales Unit of Measure',
  DELIV_QTY_SU STRING,
  CONF_SCHED_LINE_QTY_SU STRING,
  CORR_SCHED_LINE_QTY_SU STRING,
  REQ_SCHEDULE_LINE_QTY_BU STRING,
  REQ_SCHEDULE_LINE_QTY_SU STRING,
  CON_SCHED_LINE_NET_VALUE_DC STRING,
  CON_SCHED_LINE_NET_VALUE_LC STRING,
  REQ_SCHED_LINE_NET_VALUE_DC STRING,
  REQ_SCHED_LINE_NET_VALUE_LC STRING,
  COST_DC DECIMAL(20,2) COMMENT 'Costs in Doccument Currency',
  COST_LC DECIMAL(35,2) COMMENT 'Costs in Local Currency',
  SO_DOC_ITEM_CREATION_DATE DATE COMMENT 'Sales Order Item Creation Date',
  SO_DOC_ITEM_PROCESSING_STATUS VARCHAR(2) COMMENT 'Sales Order Item Processing Status ID',
  UNIT_OF_WT_ID VARCHAR(3) COMMENT 'Unit of Weight',
  UNIT_OF_VOL_ID VARCHAR(3) COMMENT 'Unit of Volume',
  TARGET_QUOM VARCHAR(3) COMMENT 'Target Quantity Unit of Measure',
  UOM_ID STRING,
  DISTR_CHAN_ID STRING,
  DIVISION_ID VARCHAR(2) COMMENT 'Division ID',
  LOG_SOURCE_SYSTEM_ID VARCHAR(10) COMMENT 'Logical Source System ID',
  MATERIAL_PRICING_GROUP_ID VARCHAR(10) COMMENT 'Material Pricing Group ID',
  CUST_PO_ID VARCHAR(20) COMMENT 'Customer Purchase Order ID',
  CUST_PO_DATE DATE COMMENT 'Customer Purchase Order Date',
  PARTNER_COMPANY_ID VARCHAR(10) COMMENT 'Partner Company ID',
  ETLLastModifiedDate DATE)
USING delta
LOCATION 'abfss://raw@zpdatacoresadpemea.dfs.core.windows.net/landing/bnlx/fico_fact_sd_order'
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')