CREATE VIEW emea_quality_int_bnlx.vw_fact_prep_sap_ch_be_remove_prod (
  `0accnt_asgn`,
  `0billtoprty`,
  `0bill_type`,
  `0calday`,
  `0calmonth`,
  `0calquart1`,
  `0calquarter`,
  `0calweek`,
  `0calyear`,
  `0comp_code`,
  `0coorder`,
  `0country`,
  `0co_area`,
  `0cs_chart`,
  `0cs_dimen`,
  `0cs_doctype`,
  `0cs_item`,
  `0curkey_gc`,
  `0curkey_lc`,
  `0curkey_tc`,
  `0customer`,
  `0cust_sales`,
  `0distr_chan`,
  `0division`,
  `0doc_type`,
  `0fiscper`,
  `0fiscper3`,
  `0fiscvarnt`,
  `0fiscyear`,
  `0gi_date`,
  `0gl_account`,
  `0material`,
  `0matl_grp_1`,
  `0payer`,
  `0pcompany`,
  `0plant`,
  `0prod_hier`,
  `0pstng_date`,
  `0salesorg`,
  `0ship_to`,
  `0sold_to`,
  `0unit`,
  `0version`,
  `0vtype`,
  dbg,
  dctry_fd,
  dpc,
  drespl1,
  drespo,
  dru,
  dsbe,
  dvf,
  d_msrca,
  d_cs_grpa,
  d_xdisco,
  d_xgross,
  d_xnetsal,
  rk_quantity,
  rk_fc1_quantity,
  rk_fc2_quantity,
  rk_fc3_quantity,
  rk_quantity_pln,
  ck_net_sales_amt_act,
  ck_discnt_amt_act,
  ck_disc_cash_act,
  ck_disc_act,
  ck_gross_qnty_act,
  ck_rebates_act,
  ck_rebates_other_act,
  ck_returns_act,
  ck_not_assigned_act,
  rk_fc1_amount,
  rk_fc2_amount,
  rk_fc3_amount,
  ck_gross_sales_amt_pln,
  ck_net_sales_amt_pln,
  ck_discnt_amt_pln,
  ck_disc_cash_pln,
  ck_disc_pln,
  ck_gross_qnty_pln,
  ck_rebates_pln,
  ck_rebates_other_pln,
  ck_returns_pln,
  ck_not_assigned_pln,
  ck_gross_sales_amt_act,
  ck_secondary_rebates_act,
  ck_secondary_rebates_pln,
  `0material_short`,
  `0cust_sales_short`,
  rls_auth_sid)
WITH SCHEMA BINDING
AS WITH CTE_Material_Mapping AS (
  SELECT
    COUNTRY_CODE,
    PORTFOLIO_MANAGEMENT,
    SAP_MATERIAL_CODE,
    TRIM(LEADING '0' FROM SAP_MATERIAL_CODE) AS SAP_MATERIAL_SHORT
  FROM
    emea_quality_int_bnlx.man_ch_product_mapping
  WHERE
    COUNTRY_CODE = 'BE'
    
),

CTE_fact_copaf_ext_p_new AS (
  SELECT
    0ACCNT_ASGN,
    0BILLTOPRTY,
    0BILL_TYPE,
    0CALDAY,
    0CALMONTH,
    0CALQUART1,
    0CALQUARTER,
    0CALWEEK,
    0CALYEAR,
    0COMP_CODE,
    0COORDER,
    0COUNTRY,
    0CO_AREA,
    0CS_CHART,
    0CS_DIMEN,
    0CS_DOCTYPE,
    0CS_ITEM,
    0CURKEY_GC,
    0CURKEY_LC,
    0CURKEY_TC,
    0CUSTOMER,
    0CUST_SALES,
    0DISTR_CHAN,
    0DIVISION,
    0DOC_TYPE,
    0FISCPER,
    0FISCPER3,
    0FISCVARNT,
    0FISCYEAR,
    0GI_DATE,
    0GL_ACCOUNT,
    0MATERIAL,
    0MATL_GRP_1,
    0PAYER,
    0PCOMPANY,
    0PLANT,
    0PROD_HIER,
    0PSTNG_DATE,
    0SALESORG,
    0SHIP_TO,
    0SOLD_TO,
    0UNIT,
    0VERSION,
    0VTYPE,
    DBG,
    DCTRY_FD,
    DPC,
    DRESPL1,
    DRESPO,
    DRU,
    DSBE,
    DVF,
    D_MSRCA,
    D_CS_GRPA,
    D_XDISCO,
    D_XGROSS,
    D_XNETSAL,
    RK_QUANTITY,
    RK_FC1_QUANTITY,
    RK_FC2_QUANTITY,
    RK_FC3_QUANTITY,
    RK_QUANTITY_PLN,
    CK_NET_SALES_AMT_ACT,
    CK_DISCNT_AMT_ACT,
    CK_DISC_CASH_ACT,
    CK_DISC_ACT,
    CK_GROSS_QNTY_ACT,
    CK_REBATES_ACT,
    CK_REBATES_OTHER_ACT,
    CK_RETURNS_ACT,
    CK_NOT_ASSIGNED_ACT,
    RK_FC1_AMOUNT,
    RK_FC2_AMOUNT,
    RK_FC3_AMOUNT,
    CK_GROSS_SALES_AMT_PLN,
    CK_NET_SALES_AMT_PLN,
    CK_DISCNT_AMT_PLN,
    CK_DISC_CASH_PLN,
    CK_DISC_PLN,
    CK_GROSS_QNTY_PLN,
    CK_REBATES_PLN,
    CK_REBATES_OTHER_PLN,
    CK_RETURNS_PLN,
    CK_NOT_ASSIGNED_PLN,
    CK_GROSS_SALES_AMT_ACT,
    CK_SECONDARY_REBATES_ACT,
    CK_SECONDARY_REBATES_PLN,
    TRIM(LEADING '0' FROM 0MATERIAL) AS 0MATERIAL_SHORT,
    TRIM(LEADING '0' FROM 0CUST_SALES) AS 0CUST_SALES_SHORT,
    RLS_AUTH_SID
  FROM
    emea_quality_int_bnlx.fact_copaf_ext_p_new WHERE 0COMP_CODE = '0159' AND DBG = '16' AND 0CUST_SALES != '0003148502'
)

  SELECT
    0ACCNT_ASGN,
    0BILLTOPRTY,
    0BILL_TYPE,
    0CALDAY,
    0CALMONTH,
    0CALQUART1,
    0CALQUARTER,
    0CALWEEK,
    0CALYEAR,
    0COMP_CODE,
    0COORDER,
    0COUNTRY,
    0CO_AREA,
    0CS_CHART,
    0CS_DIMEN,
    0CS_DOCTYPE,
    0CS_ITEM,
    0CURKEY_GC,
    0CURKEY_LC,
    0CURKEY_TC,
    0CUSTOMER,
    0CUST_SALES,
    0DISTR_CHAN,
    0DIVISION,
    0DOC_TYPE,
    0FISCPER,
    0FISCPER3,
    0FISCVARNT,
    0FISCYEAR,
    0GI_DATE,
    0GL_ACCOUNT,
    0MATERIAL,
    0MATL_GRP_1,
    0PAYER,
    0PCOMPANY,
    0PLANT,
    0PROD_HIER,
    0PSTNG_DATE,
    0SALESORG,
    0SHIP_TO,
    0SOLD_TO,
    0UNIT,
    0VERSION,
    0VTYPE,
    DBG,
    DCTRY_FD,
   
    DPC,
    DRESPL1,
    DRESPO,
    DRU,
    DSBE,
    DVF,
    D_MSRCA,
    D_CS_GRPA,
    D_XDISCO,
    D_XGROSS,
    D_XNETSAL,
   SUM(RK_QUANTITY) AS RK_QUANTITY
,SUM(RK_FC1_QUANTITY) AS RK_FC1_QUANTITY
,SUM(RK_FC2_QUANTITY) AS RK_FC2_QUANTITY
,SUM(RK_FC3_QUANTITY) AS RK_FC3_QUANTITY
,SUM(RK_QUANTITY_PLN) AS RK_QUANTITY_PLN
,SUM(CK_NET_SALES_AMT_ACT) AS CK_NET_SALES_AMT_ACT
,SUM(CK_DISCNT_AMT_ACT) AS CK_DISCNT_AMT_ACT
,SUM(CK_DISC_CASH_ACT) AS CK_DISC_CASH_ACT
,SUM(CK_DISC_ACT) AS CK_DISC_ACT
,SUM(CK_GROSS_QNTY_ACT) AS CK_GROSS_QNTY_ACT
,SUM(CK_REBATES_ACT) AS CK_REBATES_ACT
,SUM(CK_REBATES_OTHER_ACT) AS CK_REBATES_OTHER_ACT
,SUM(CK_RETURNS_ACT) AS CK_RETURNS_ACT
,SUM(CK_NOT_ASSIGNED_ACT) AS CK_NOT_ASSIGNED_ACT
,SUM(RK_FC1_AMOUNT) AS RK_FC1_AMOUNT
,SUM(RK_FC2_AMOUNT) AS RK_FC2_AMOUNT
,SUM(RK_FC3_AMOUNT) AS RK_FC3_AMOUNT
,SUM(CK_GROSS_SALES_AMT_PLN) AS CK_GROSS_SALES_AMT_PLN
,SUM(CK_NET_SALES_AMT_PLN) AS CK_NET_SALES_AMT_PLN
,SUM(CK_DISCNT_AMT_PLN) AS CK_DISCNT_AMT_PLN
,SUM(CK_DISC_CASH_PLN) AS CK_DISC_CASH_PLN
,SUM(CK_DISC_PLN) AS CK_DISC_PLN
,SUM(CK_GROSS_QNTY_PLN) AS CK_GROSS_QNTY_PLN
,SUM(CK_REBATES_PLN) AS CK_REBATES_PLN
,SUM(CK_REBATES_OTHER_PLN) AS CK_REBATES_OTHER_PLN
,SUM(CK_RETURNS_PLN) AS CK_RETURNS_PLN
,SUM(CK_NOT_ASSIGNED_PLN) AS CK_NOT_ASSIGNED_PLN
,SUM(CK_GROSS_SALES_AMT_ACT) AS CK_GROSS_SALES_AMT_ACT
,SUM(CK_SECONDARY_REBATES_ACT) AS CK_SECONDARY_REBATES_ACT
,SUM(CK_SECONDARY_REBATES_PLN) AS CK_SECONDARY_REBATES_PLN,
   0MATERIAL_SHORT,
   0CUST_SALES_SHORT,
   RLS_AUTH_SID
 FROM CTE_fact_copaf_ext_p_new 
 LEFT JOIN CTE_Material_Mapping
 ON CTE_fact_copaf_ext_p_new.0MATERIAL_SHORT=CTE_Material_Mapping.SAP_MATERIAL_SHORT
 WHERE IFNULL(CTE_Material_Mapping.PORTFOLIO_MANAGEMENT, '-1') != 'Delisted'
 GROUP BY 
  0ACCNT_ASGN,
  0BILLTOPRTY,
  0BILL_TYPE,
  0CALDAY,
  0CALMONTH,
  0CALQUART1,
  0CALQUARTER,
  0CALWEEK,
  0CALYEAR,
  0COMP_CODE,
  0COORDER,
  0COUNTRY,
  0CO_AREA,
  0CS_CHART,
  0CS_DIMEN,
  0CS_DOCTYPE,
  0CS_ITEM,
  0CURKEY_GC,
  0CURKEY_LC,
  0CURKEY_TC,
  0CUSTOMER,
  0CUST_SALES,
  0DISTR_CHAN,
  0DIVISION,
  0DOC_TYPE,
  0FISCPER,
  0FISCPER3,
  0FISCVARNT,
  0FISCYEAR,
  0GI_DATE,
  0GL_ACCOUNT,
  0MATERIAL,
  0MATL_GRP_1,
  0PAYER,
  0PCOMPANY,
  0PLANT,
  0PROD_HIER,
  0PSTNG_DATE,
  0SALESORG,
  0SHIP_TO,
  0SOLD_TO,
  0UNIT,
  0VERSION,
  0VTYPE,
  DBG,
  DCTRY_FD,
  DPC,
  DRESPL1,
  DRESPO,
  DRU,
  DSBE,
  DVF,
  D_MSRCA,
  D_CS_GRPA,
  D_XDISCO,
  D_XGROSS,
  D_XNETSAL,
  0MATERIAL_SHORT,
   0CUST_SALES_SHORT,
   RLS_AUTH_SID