CREATE VIEW emea_quality_int_bnlx.vw_fact_prep_sap_ch_copa_sales_objectives_be (
  `0accnt_asgn`,
  `0billtoprty`,
  `0bill_type`,
  `0calday`,
  `0calmonth`,
  `0calquart1`,
  `0calquarter`,
  `0calweek`,
  `0calyear`,
  `0comp_code`,
  `0coorder`,
  `0country`,
  `0co_area`,
  `0cs_chart`,
  `0cs_dimen`,
  `0cs_doctype`,
  `0cs_item`,
  `0curkey_gc`,
  `0curkey_lc`,
  `0curkey_tc`,
  `0customer`,
  `0cust_sales`,
  `0distr_chan`,
  `0division`,
  `0doc_type`,
  `0fiscper`,
  `0fiscper3`,
  `0fiscvarnt`,
  `0fiscyear`,
  `0gi_date`,
  `0gl_account`,
  `0material`,
  `0matl_grp_1`,
  `0payer`,
  `0pcompany`,
  `0plant`,
  `0prod_hier`,
  `0pstng_date`,
  `0salesorg`,
  `0ship_to`,
  `0sold_to`,
  `0unit`,
  `0version`,
  `0vtype`,
  dbg,
  dctry_fd,
  dpc,
  drespl1,
  drespo,
  dru,
  dsbe,
  dvf,
  d_msrca,
  d_cs_grpa,
  d_xdisco,
  d_xgross,
  d_xnetsal,
  rk_quantity,
  rk_fc1_quantity,
  rk_fc2_quantity,
  rk_fc3_quantity,
  rk_quantity_pln,
  ck_net_sales_amt_act,
  ck_discnt_amt_act,
  ck_disc_cash_act,
  ck_disc_act,
  ck_gross_qnty_act,
  ck_rebates_act,
  ck_rebates_other_act,
  ck_returns_act,
  ck_not_assigned_act,
  rk_fc1_amount,
  rk_fc2_amount,
  rk_fc3_amount,
  ck_gross_sales_amt_pln,
  ck_net_sales_amt_pln,
  ck_discnt_amt_pln,
  ck_disc_cash_pln,
  ck_disc_pln,
  ck_gross_qnty_pln,
  ck_rebates_pln,
  ck_rebates_other_pln,
  ck_returns_pln,
  ck_not_assigned_pln,
  ck_gross_sales_amt_act,
  ck_secondary_rebates_act,
  ck_secondary_rebates_pln,
  `0material_short`,
  `0cust_code_trim`,
  country_code,
  cluster,
  channel,
  organization,
  objective_type,
  date,
  objective_eur,
  rls_auth_sid)
WITH SCHEMA BINDING
AS WITH CTE_copa_ch_be AS 
  (
  SELECT
    0ACCNT_ASGN,
    0BILLTOPRTY,
    0BILL_TYPE,
    0CALDAY,
    0CALMONTH,
    0CALQUART1,
    0CALQUARTER,
    0CALWEEK,
    0CALYEAR,
    0COMP_CODE,
    0COORDER,
    0COUNTRY,
    0CO_AREA,
    0CS_CHART,
    0CS_DIMEN,
    0CS_DOCTYPE,
    0CS_ITEM,
    0CURKEY_GC,
    0CURKEY_LC,
    0CURKEY_TC,
    0CUSTOMER,
    0CUST_SALES,
    0DISTR_CHAN,
    0DIVISION,
    0DOC_TYPE,
    0FISCPER,
    0FISCPER3,
    0FISCVARNT,
    0FISCYEAR,
    0GI_DATE,
    0GL_ACCOUNT,
    0MATERIAL,
    0MATL_GRP_1,
    0PAYER,
    0PCOMPANY,
    0PLANT,
    0PROD_HIER,
    0PSTNG_DATE,
    0SALESORG,
    0SHIP_TO,
    0SOLD_TO,
    0UNIT,
    0VERSION,
    0VTYPE,
    DBG,
    DCTRY_FD,
    DPC,
    DRESPL1,
    DRESPO,
    DRU,
    DSBE,
    DVF,
    D_MSRCA,
    D_CS_GRPA,
    D_XDISCO,
    D_XGROSS,
    D_XNETSAL,
    RK_QUANTITY,
    RK_FC1_QUANTITY,
    RK_FC2_QUANTITY,
    RK_FC3_QUANTITY,
    RK_QUANTITY_PLN,
    CK_NET_SALES_AMT_ACT,
    CK_DISCNT_AMT_ACT,
    CK_DISC_CASH_ACT,
    CK_DISC_ACT,
    CK_GROSS_QNTY_ACT,
    CK_REBATES_ACT,
    CK_REBATES_OTHER_ACT,
    CK_RETURNS_ACT,
    CK_NOT_ASSIGNED_ACT,
    RK_FC1_AMOUNT,
    RK_FC2_AMOUNT,
    RK_FC3_AMOUNT,
    CK_GROSS_SALES_AMT_PLN,
    CK_NET_SALES_AMT_PLN,
    CK_DISCNT_AMT_PLN,
    CK_DISC_CASH_PLN,
    CK_DISC_PLN,
    CK_GROSS_QNTY_PLN,
    CK_REBATES_PLN,
    CK_REBATES_OTHER_PLN,
    CK_RETURNS_PLN,
    CK_NOT_ASSIGNED_PLN,
    CK_GROSS_SALES_AMT_ACT,
    CK_SECONDARY_REBATES_ACT,
    CK_SECONDARY_REBATES_PLN,
    0MATERIAL_SHORT,
   TO_DATE(CONCAT(0CALMONTH, '01'), 'yyyyMMdd')  AS COPA_DATE,
   0CUST_SALES_SHORT AS 0CUST_CODE_TRIM,
   RLS_AUTH_SID
  FROM  emea_quality_int_bnlx.vw_fact_prep_sap_ch_be_remove_prod
  )
  
  ,CTE_cust_mapping
  AS 
  (

SELECT country_code,`cluster`,channel,organization,sap_customer_code,TRIM(LEADING '0' FROM SAP_CUSTOMER_CODE) AS sap_customer_code_trim  FROM  emea_quality_int_bnlx.man_ch_customer_mapping WHERE COUNTRY_CODE = 'BE'

  ),
  CTE_sales_objectives AS 
  (

   SELECT objective_type,country_code,channel,organization,date,objective_eur,`cluster`
 FROM  emea_quality_int_bnlx.man_ch_sales_objective_be
  )
SELECT 
`0accnt_asgn`,
  `0billtoprty`,
  `0bill_type`,
  `0calday`,
  `0calmonth`,
  `0calquart1`,
  `0calquarter`,
  `0calweek`,
  `0calyear`,
  `0comp_code`,
  `0coorder`,
  `0country`,
  `0co_area`,
  `0cs_chart`,
  `0cs_dimen`,
  `0cs_doctype`,
  `0cs_item`,
  `0curkey_gc`,
  `0curkey_lc`,
  `0curkey_tc`,
  `0customer`,
  `0cust_sales`,
  `0distr_chan`,
  `0division`,
  `0doc_type`,
  `0fiscper`,
  `0fiscper3`,
  `0fiscvarnt`,
  `0fiscyear`,
  `0gi_date`,
  `0gl_account`,
  `0material`,
  `0matl_grp_1`,
  `0payer`,
  `0pcompany`,
  `0plant`,
  `0prod_hier`,
  `0pstng_date`,
  `0salesorg`,
  `0ship_to`,
  `0sold_to`,
  `0unit`,
  `0version`,
  `0vtype`,
  dbg,
  dctry_fd,
  dpc,
  drespl1,
  drespo,
  dru,
  dsbe,
  dvf,
  d_msrca,
  d_cs_grpa,
  d_xdisco,
  d_xgross,
  d_xnetsal,
SUM(rk_quantity) as rk_quantity,
SUM(rk_fc1_quantity) as rk_fc1_quantity,
SUM(rk_fc2_quantity) as rk_fc3_quantity,
SUM(rk_fc3_quantity) as rk_fc3_quantity,
SUM(rk_quantity_pln) as rk_quantity_pln,
SUM(ck_net_sales_amt_act) as ck_net_sales_amt_act,
SUM(ck_discnt_amt_act) as ck_discnt_amt_act,
SUM(ck_disc_cash_act) as ck_disc_cash_act,
SUM(ck_disc_act) as ck_disc_act,
SUM(ck_gross_qnty_act) as ck_gross_qnty_act,
SUM(ck_rebates_act) as ck_rebates_act,
SUM(ck_rebates_other_act) as ck_rebates_other_act,
SUM(ck_returns_act) as ck_returns_act,
SUM(ck_not_assigned_act) as ck_not_assigned_act,
SUM(rk_fc1_amount) as rk_fc1_amount,
SUM(rk_fc2_amount) as rk_fc2_amount,
SUM(rk_fc3_amount) as rk_fc3_amount,
SUM(ck_gross_sales_amt_pln) as ck_gross_sales_amt_pln,
SUM(ck_net_sales_amt_pln) as ck_net_sales_amt_pln,
SUM(ck_discnt_amt_pln) as ck_discnt_amt_pln,
SUM(ck_disc_cash_pln) as ck_disc_cash_pln,
SUM(ck_disc_pln) as ck_disc_pln,
SUM(ck_gross_qnty_pln) as ck_gross_qnty_pln,
SUM(ck_rebates_pln) as ck_rebates_pln,
SUM(ck_rebates_other_pln) as ck_rebates_other_pln,
SUM(ck_returns_pln) as ck_returns_pln,
SUM(ck_not_assigned_pln) as ck_not_assigned_pln,
SUM(ck_gross_sales_amt_act) as ck_gross_sales_amt_act,
SUM(ck_secondary_rebates_act) as ck_secondary_rebates_act,
SUM(ck_secondary_rebates_pln) as ck_secondary_rebates_pln,
  `0material_short`,
  `0cust_code_trim`,
  country_code,
  cluster,
  channel,
  organization,
  objective_type,
  date,
  sum(objective_eur) as objective_eur,
  rls_auth_sid
FROM 
(
  SELECT
    0ACCNT_ASGN,
    0BILLTOPRTY,
    0BILL_TYPE,
    0CALDAY,
    0CALMONTH,
    0CALQUART1,
    0CALQUARTER,
    0CALWEEK,
    0CALYEAR,
    0COMP_CODE,
    0COORDER,
    0COUNTRY,
    0CO_AREA,
    0CS_CHART,
    0CS_DIMEN,
    0CS_DOCTYPE,
    0CS_ITEM,
    0CURKEY_GC,
    0CURKEY_LC,
    0CURKEY_TC,
    0CUSTOMER,
    0CUST_SALES,
    0DISTR_CHAN,
    0DIVISION,
    0DOC_TYPE,
    0FISCPER,
    0FISCPER3,
    0FISCVARNT,
    0FISCYEAR,
    0GI_DATE,
    0GL_ACCOUNT,
    0MATERIAL,
    0MATL_GRP_1,
    0PAYER,
    0PCOMPANY,
    0PLANT,
    0PROD_HIER,
    0PSTNG_DATE,
    0SALESORG,
    0SHIP_TO,
    0SOLD_TO,
    0UNIT,
    0VERSION,
    0VTYPE,
    DBG,
    DCTRY_FD,
    DPC,
    DRESPL1,
    DRESPO,
    DRU,
    DSBE,
    DVF,
    D_MSRCA,
    D_CS_GRPA,
    D_XDISCO,
    D_XGROSS,
    D_XNETSAL,
    RK_QUANTITY,
    RK_FC1_QUANTITY,
    RK_FC2_QUANTITY,
    RK_FC3_QUANTITY,
    RK_QUANTITY_PLN,
    CK_NET_SALES_AMT_ACT,
    CK_DISCNT_AMT_ACT,
    CK_DISC_CASH_ACT,
    CK_DISC_ACT,
    CK_GROSS_QNTY_ACT,
    CK_REBATES_ACT,
    CK_REBATES_OTHER_ACT,
    CK_RETURNS_ACT,
    CK_NOT_ASSIGNED_ACT,
    RK_FC1_AMOUNT,
    RK_FC2_AMOUNT,
    RK_FC3_AMOUNT,
    CK_GROSS_SALES_AMT_PLN,
    CK_NET_SALES_AMT_PLN,
    CK_DISCNT_AMT_PLN,
    CK_DISC_CASH_PLN,
    CK_DISC_PLN,
    CK_GROSS_QNTY_PLN,
    CK_REBATES_PLN,
    CK_REBATES_OTHER_PLN,
    CK_RETURNS_PLN,
    CK_NOT_ASSIGNED_PLN,
    CK_GROSS_SALES_AMT_ACT,
    CK_SECONDARY_REBATES_ACT,
    CK_SECONDARY_REBATES_PLN,
    0MATERIAL_SHORT,
   0CUST_CODE_TRIM,
   CTE_cust_mapping.country_code
   , CTE_cust_mapping.`cluster`,
    CTE_cust_mapping.channel, 
    CTE_cust_mapping.organization,
    NULL AS objective_type,
    COPA_DATE AS date,
    NULL AS objective_eur,
    rls_auth_sid
  FROM  CTE_copa_ch_be
  LEFT JOIN CTE_cust_mapping ON CTE_copa_ch_be.0CUST_CODE_TRIM=CTE_cust_mapping.sap_customer_code_trim
  UNION
  SELECT
    null as 0ACCNT_ASGN,
    NULL as 0BILLTOPRTY,
    null as 0BILL_TYPE,
    null as 0CALDAY,
    null as 0CALMONTH,
    null as 0CALQUART1,
    null as 0CALQUARTER,
    null as 0CALWEEK,
    null as 0CALYEAR,
    null as 0COMP_CODE,
    null as 0COORDER,
    null as 0COUNTRY,
    null as 0CO_AREA,
    null as 0CS_CHART,
    null as 0CS_DIMEN,
    null as 0CS_DOCTYPE,
    null as 0CS_ITEM,
    null as 0CURKEY_GC,
    null as 0CURKEY_LC,
    null as 0CURKEY_TC,
    null as 0CUSTOMER,
    null as 0CUST_SALES,
    null as 0DISTR_CHAN,
    null as 0DIVISION,
    null as 0DOC_TYPE,
   
    null as 0FISCPER,
    null as 0FISCPER3,
    null as 0FISCVARNT,
    null as 0FISCYEAR,
    null as 0GI_DATE,
    null as 0GL_ACCOUNT,
    null as 0MATERIAL,
    null as 0MATL_GRP_1,
    null as 0PAYER,
    null as 0PCOMPANY,
    null as 0PLANT,
    null as 0PROD_HIER,
    null as 0PSTNG_DATE,
    null as 0SALESORG,
    null as 0SHIP_TO,
    null as 0SOLD_TO,
    null as 0UNIT,
    null as 0VERSION,
    null as 0VTYPE,
    null as DBG,
    null as DCTRY_FD,
   
    null as DPC,
    null as DRESPL1,
    null as DRESPO,
    null as DRU,
    null as DSBE,
    null as DVF,
    null as D_MSRCA,
    null as D_CS_GRPA,
    null as D_XDISCO,
    null as D_XGROSS,
    null as D_XNETSAL,
    null as RK_QUANTITY,
    null as RK_FC1_QUANTITY,
    null as RK_FC2_QUANTITY,
    null as RK_FC3_QUANTITY,
    null as RK_QUANTITY_PLN,
    null as CK_NET_SALES_AMT_ACT,
    null as CK_DISCNT_AMT_ACT,
    null as CK_DISC_CASH_ACT,
    null as CK_DISC_ACT,
    null as CK_GROSS_QNTY_ACT,
    null as CK_REBATES_ACT,
    null as CK_REBATES_OTHER_ACT,
    null as CK_RETURNS_ACT,
    null as CK_NOT_ASSIGNED_ACT,
    null as RK_FC1_AMOUNT,
    null as RK_FC2_AMOUNT,
    null as RK_FC3_AMOUNT,
    null as CK_GROSS_SALES_AMT_PLN,
    null as CK_NET_SALES_AMT_PLN,
    null as CK_DISCNT_AMT_PLN,
    null as CK_DISC_CASH_PLN,
    null as CK_DISC_PLN,
    null as CK_GROSS_QNTY_PLN,
    null as CK_REBATES_PLN,
    null as CK_REBATES_OTHER_PLN,
    null as CK_RETURNS_PLN,
    null as CK_NOT_ASSIGNED_PLN,
    null as CK_GROSS_SALES_AMT_ACT,
    null as CK_SECONDARY_REBATES_ACT,
    null as CK_SECONDARY_REBATES_PLN,
    null as 0MATERIAL_SHORT,
    null as 0CUST_CODE_TRIM,
   country_code,
   `cluster`,
    channel, 
    organization,
   objective_type,
     date,
    objective_eur,
    NULL AS rls_auth_sid
  FROM  CTE_sales_objectives
)
GROUP BY 
`0accnt_asgn`,
  `0billtoprty`,
  `0bill_type`,
  `0calday`,
  `0calmonth`,
  `0calquart1`,
  `0calquarter`,
  `0calweek`,
  `0calyear`,
  `0comp_code`,
  `0coorder`,
  `0country`,
  `0co_area`,
  `0cs_chart`,
  `0cs_dimen`,
  `0cs_doctype`,
  `0cs_item`,
  `0curkey_gc`,
  `0curkey_lc`,
  `0curkey_tc`,
  `0customer`,
  `0cust_sales`,
  `0distr_chan`,
  `0division`,
  `0doc_type`,
  `0fiscper`,
  `0fiscper3`,
  `0fiscvarnt`,
  `0fiscyear`,
  `0gi_date`,
  `0gl_account`,
  `0material`,
  `0matl_grp_1`,
  `0payer`,
  `0pcompany`,
  `0plant`,
  `0prod_hier`,
  `0pstng_date`,
  `0salesorg`,
  `0ship_to`,
  `0sold_to`,
  `0unit`,
  `0version`,
  `0vtype`,
  dbg,
  dctry_fd,
  dpc,
  drespl1,
  drespo,
  dru,
  dsbe,
  dvf,
  d_msrca,
  d_cs_grpa,
  d_xdisco,
  d_xgross,
  d_xnetsal,
  `0material_short`,
  `0cust_code_trim`,
  country_code,
  cluster,
  channel,
  organization,
  objective_type,
  date,
  rls_auth_sid