CREATE TABLE chdaa_prd_lz_emea.emea_quality_enr_ceec.dim_products (
  nr_pozwolenia STRING,
  sap_id STRING,
  sku_name STRING,
  form STRING,
  sku_short_name STRING,
  vat FLOAT,
  etl_checksum_scd1 STRING,
  status STRING,
  is_msl_list STRING,
  product_is_valid STRING,
  product_type STRING,
  lastmodifieddate DATE,
  brand_group STRING,
  exfactory_price FLOAT,
  bazyl STRING,
  is_massmarket STRING,
  is_commercial STRING,
  key_words STRING,
  product_valid_from TIMESTAMP,
  aktualnosc DATE,
  bloz7 STRING,
  product_bk STRING,
  brand STRING,
  product_source STRING,
  product_id STRING,
  ean STRING,
  fct_tool_name STRING,
  is_contracted STRING,
  active_substance_dosage STRING,
  pkwiu STRING,
  sap_name STRING,
  attribute STRING,
  etl_checksum_scd2 STRING,
  unit_of_measurement STRING,
  category STRING,
  product_valid_to TIMESTAMP,
  units_volume STRING,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/enrichment/ceec/dim_products'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')