CREATE TABLE chdaa_prd_lz_emea.emea_quality_enr_ceec.fact_transactions (
  document_id STRING,
  date_order_forward DATE,
  kpi STRING,
  distributor_comments STRING,
  estimated_compensation_value FLOAT,
  transaction_customer_id STRING,
  kamsoft_program_id STRING,
  kamsoft_program_name STRING,
  rep_comments STRING,
  transaction_product_bk STRING,
  sales_type STRING,
  date_end_discount_packet DATE,
  date_corrected DATE,
  exfactory_price FLOAT,
  transaction_time_id TIMESTAMP,
  sell_in_volume_before_correction FLOAT,
  additional_info STRING,
  purchase_type STRING,
  transaction_customer_bk BIGINT,
  sales_time STRING,
  date_purchase DATE,
  product_objections STRING,
  distributor STRING,
  discount_packet STRING,
  transaction_source STRING,
  internal_comments STRING,
  date_distributor_sales DATE,
  transaction_row_id STRING,
  estimated_order_value_exfactory_price FLOAT,
  psdt_akt_synch TIMESTAMP,
  chain_customer_name STRING,
  chain_order_id STRING,
  transaction_product_id STRING,
  order_status STRING,
  estimated_order_value_ex_factory_price_after_compensation FLOAT,
  expiry_date DATE,
  discount_percentage FLOAT,
  global_id STRING,
  batch_number STRING,
  volume FLOAT,
  order_id STRING,
  data_delivery_date DATE,
  date_start_discount_packet DATE,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
PARTITIONED BY (transaction_source, data_delivery_date)
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/enrichment/ceec/fact_transactions'
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')