CREATE VIEW emea_quality_enr_ceec.vw_f_transactions_user_view (
  DATA_DELIVERY_DATE,
  KPI,
  Kamsoft_program_name,
  Kamsoft_program_ID,
  Date_purchase,
  Expiry_date,
  Batch_number,
  Distributor,
  Sales_type,
  Document_ID,
  Order_ID,
  Sales_time,
  Purchase_type,
  Date_distributor_sales,
  Discount_packet,
  Date_start_discount_packet,
  Date_end_discount_packet,
  Date_order_forward,
  Chain_order_ID,
  Chain_Customer_name,
  Order_status,
  Rep_comments,
  Distributor_comments,
  Internal_comments,
  Product_objections,
  Additional_info,
  TRANSACTION_SOURCE,
  transaction_time_time_id,
  transaction_customer_customer_id,
  TRANSACTION_CUSTOMER_BK,
  transaction_product_product_id,
  TRANSACTION_PRODUCT_BK,
  PSDT_AKT_SYNCH,
  Volume,
  sell_in_volume_before_correction,
  Discount_percentage,
  ExFactory_price_1,
  Estimated_compensation_value,
  Estimated_order_value_exfactory_price,
  Estimated_order_value_ex_factory_price_after_compensation,
  Date_corrected,
  adress,
  area_commercial,
  area_education,
  attributes,
  behind_counter_exposition,
  behind_glass_exposition,
  chain_customer_account,
  chain_type,
  city,
  commercial_segment,
  contract,
  customer_bk,
  customer_change_timestamp,
  customer_group,
  customer_id,
  customer_is_valid,
  customer_lad,
  customer_source,
  customer_valid_from,
  customer_valid_to,
  dnv_commercial,
  dnv_education,
  education_segment,
  email,
  external_source,
  group_owner,
  group_type,
  id_acres,
  id_chain_customer,
  id_customer,
  id_esalesweb,
  id_external_reporting,
  id_farmaprom,
  importance,
  iqvia_brick,
  is_dermatological,
  is_kamsoft,
  is_ordering,
  is_self_service,
  kamsoft_agreement,
  last_visit_commercial,
  last_visit_education,
  name_chain_customer,
  nip,
  pharmacy_name,
  pharmacy_status,
  pharmacy_type,
  phone_number,
  position,
  rep_id_commercial,
  rep_id_education,
  rep_name_commercial,
  rep_name_education,
  store_window,
  zip_code,
  active_substance_dosage,
  aktualnosc,
  attribute,
  bazyl,
  bloz7,
  brand,
  brand_group,
  category,
  ean,
  exfactory_price,
  fct_tool_name,
  form,
  is_commercial,
  is_contracted,
  is_massmarket,
  is_msl_list,
  key_words,
  nr_pozwolenia,
  pkwiu,
  product_bk,
  product_id,
  product_is_valid,
  product_type,
  product_valid_from,
  product_valid_to,
  sap_id,
  sap_name,
  sku_name,
  sku_short_name,
  status,
  unit_of_measurement,
  units_volume,
  vat,
  product_source,
  cur_adress,
  cur_area_commercial,
  cur_area_education,
  cur_attributes,
  cur_behind_counter_exposition,
  cur_behind_glass_exposition,
  cur_chain_customer_account,
  cur_chain_type,
  cur_city,
  cur_commercial_segment,
  cur_contract,
  cur_customer_bk,
  cur_customer_change_timestamp,
  cur_customer_group,
  cur_customer_id,
  cur_customer_is_valid,
  cur_customer_lad,
  cur_customer_source,
  cur_customer_valid_from,
  cur_customer_valid_to,
  cur_dnv_commercial,
  cur_dnv_education,
  cur_education_segment,
  cur_email,
  cur_external_source,
  cur_group_owner,
  cur_group_type,
  cur_id_acres,
  cur_id_chain_customer,
  cur_id_customer,
  cur_id_esalesweb,
  cur_id_external_reporting,
  cur_id_farmaprom,
  cur_importance,
  cur_iqvia_brick,
  cur_is_dermatological,
  cur_is_kamsoft,
  cur_is_ordering,
  cur_is_self_service,
  cur_kamsoft_agreement,
  cur_last_visit_commercial,
  cur_last_visit_education,
  cur_name_chain_customer,
  cur_nip,
  cur_pharmacy_name,
  cur_pharmacy_status,
  cur_pharmacy_type,
  cur_phone_number,
  cur_position,
  cur_rep_id_commercial,
  cur_rep_id_education,
  cur_rep_name_commercial,
  cur_rep_name_education,
  cur_store_window,
  cur_zip_code,
  rep_email_commercial,
  rep_email_commercial_2,
  time_id,
  year,
  quarter,
  month,
  week_of_year,
  day_of_year,
  day_of_month,
  day_of_week,
  year_quarter,
  year_month,
  f_transaction_key,
  ETLLastModifiedDate)
WITH SCHEMA BINDING
AS (
    SELECT  
Trans.DATA_DELIVERY_DATE,
Trans.KPI,
Trans.Kamsoft_program_name,
Trans.Kamsoft_program_ID,
Trans.Date_purchase,
Trans.Expiry_date,
Trans.Batch_number,
Trans.Distributor,
Trans.Sales_type,
Trans.Document_ID,
Trans.Order_ID,
Trans.Sales_time,
Trans.Purchase_type,
Trans.Date_distributor_sales,
Trans.Discount_packet,
Trans.Date_start_discount_packet,
Trans.Date_end_discount_packet,
Trans.Date_order_forward,
Trans.Chain_order_ID,
Trans.Chain_Customer_name,
Trans.Order_status,
Trans.Rep_comments,
Trans.Distributor_comments,
Trans.Internal_comments,
Trans.Product_objections,
Trans.Additional_info,
Trans.TRANSACTION_SOURCE,
Trans.transaction_time_id as transaction_time_time_id,
Trans.transaction_customer_id as transaction_customer_customer_id,
Trans.TRANSACTION_CUSTOMER_BK,
Trans.transaction_product_id AS transaction_product_product_id,
Trans.TRANSACTION_PRODUCT_BK,
Trans.PSDT_AKT_SYNCH,
CAST(SUM(Trans.Volume) AS DECIMAL(18, 2)) AS Volume,
CAST(SUM(Trans.sell_in_volume_before_correction) AS DECIMAL(18, 2)) AS sell_in_volume_before_correction,
CAST(Trans.Discount_percentage AS DECIMAL(18, 2)) AS Discount_percentage,
CAST(Trans.exfactory_price AS DECIMAL(18, 2)) as ExFactory_price_1,
CAST(SUM(Trans.Estimated_compensation_value) AS DECIMAL(18, 2)) AS Estimated_compensation_value,
CAST(SUM(Trans.Estimated_order_value_exfactory_price) AS DECIMAL(18, 2)) AS Estimated_order_value_exfactory_price,
CAST(SUM(Trans.Estimated_order_value_ex_factory_price_after_compensation) AS DECIMAL(18, 2)) AS Estimated_order_value_ex_factory_price_after_compensation,
Trans.Date_corrected,
cust.adress,
cust.area_commercial,
cust.area_education,
cust.attributes,
cust.behind_counter_exposition,
cust.behind_glass_exposition,
cust.chain_customer_account,
cust.chain_type,
cust.city,
cust.commercial_segment,
cust.contract,
cust.customer_bk,
cust.customer_valid_from customer_change_timestamp,
--cust.customer_change_type,
cust.customer_group,
cust.customer_id,
cust.customer_is_valid,
cust.customer_lad,
cust.customer_source,
cust.customer_valid_from,
cust.customer_valid_to,
cust.dnv_commercial,
cust.dnv_education,
cust.education_segment,
cust.email,
cust.external_source,
cust.group_owner,
cust.group_type,
cust.id_acres,
cust.id_chain_customer,
cust.id_customer,
cust.id_esalesweb,
cust.id_external_reporting,
cust.id_farmaprom,
cust.importance,
cust.iqvia_brick,
cust.is_dermatological,
cust.is_kamsoft,
cust.is_ordering,
cust.is_self_service,
cust.kamsoft_agreement,
cust.last_visit_commercial,
cust.last_visit_education,
cust.name_chain_customer,
cust.nip,
cust.pharmacy_name,
cust.pharmacy_status,
cust.pharmacy_type,
cust.phone_number,
cust.position,
cust.rep_id_commercial,
cust.rep_id_education,
cust.rep_name_commercial,
cust.rep_name_education,
cust.store_window,
cust.zip_code,
prod.active_substance_dosage,
prod.aktualnosc,
prod.attribute,
prod.bazyl,
prod.bloz7,
prod.brand,
prod.brand_group,
prod.category,
prod.ean,
CAST(prod.exfactory_price AS DECIMAL(18, 2)) as exfactory_price,
prod.fct_tool_name,
prod.form,
prod.is_commercial,
prod.is_contracted,
prod.is_massmarket,
prod.is_msl_list,
prod.key_words,
prod.nr_pozwolenia,
prod.pkwiu,
prod.product_bk,
prod.product_id,
prod.product_is_valid,
prod.product_type,
prod.product_valid_from,
prod.product_valid_to,
prod.sap_id,
prod.sap_name,
prod.sku_name,
prod.sku_short_name,
prod.status,
prod.unit_of_measurement,
prod.units_volume,
CAST(prod.vat AS DECIMAL(18, 2)) as vat,
prod.product_source,
cust1.adress AS cur_adress,
cust1.area_commercial AS cur_area_commercial,
cust1.area_education AS cur_area_education,
cust1.attributes AS cur_attributes,
cust1.behind_counter_exposition AS cur_behind_counter_exposition,
cust1.behind_glass_exposition AS cur_behind_glass_exposition,
cust1.chain_customer_account AS cur_chain_customer_account,
cust1.chain_type AS cur_chain_type,
cust1.city AS cur_city,
cust1.commercial_segment AS cur_commercial_segment,
cust1.contract AS cur_contract,
cust1.customer_bk AS cur_customer_bk,
cust1.customer_valid_from AS cur_customer_change_timestamp,
--cust1.customer_change_type AS cur_customer_change_type,
cust1.customer_group AS cur_customer_group,
cust1.customer_id AS cur_customer_id,
cust1.customer_is_valid AS cur_customer_is_valid,
cust1.customer_lad AS cur_customer_lad,
cust1.customer_source AS cur_customer_source,
cust1.customer_valid_from AS cur_customer_valid_from,
cust1.customer_valid_to AS cur_customer_valid_to,
cust1.dnv_commercial AS cur_dnv_commercial,
cust1.dnv_education AS cur_dnv_education,
cust1.education_segment AS cur_education_segment,
cust1.email AS cur_email,
cust1.external_source AS cur_external_source,
cust1.group_owner AS cur_group_owner,
cust1.group_type AS cur_group_type,
cust1.id_acres AS cur_id_acres,
cust1.id_chain_customer AS cur_id_chain_customer,
cust1.id_customer AS cur_id_customer,
cust1.id_esalesweb AS cur_id_esalesweb,
cust1.id_external_reporting AS cur_id_external_reporting,
cust1.id_farmaprom AS cur_id_farmaprom,
cust1.importance AS cur_importance,
cust1.iqvia_brick AS cur_iqvia_brick,
cust1.is_dermatological AS cur_is_dermatological,
cust1.is_kamsoft AS cur_is_kamsoft,
cust1.is_ordering AS cur_is_ordering,
cust1.is_self_service AS cur_is_self_service,
cust1.kamsoft_agreement AS cur_kamsoft_agreement,
cust1.last_visit_commercial AS cur_last_visit_commercial,
cust1.last_visit_education AS cur_last_visit_education,
cust1.name_chain_customer AS cur_name_chain_customer,
cust1.nip AS cur_nip,
cust1.pharmacy_name AS cur_pharmacy_name,
cust1.pharmacy_status AS cur_pharmacy_status,
cust1.pharmacy_type AS cur_pharmacy_type,
cust1.phone_number AS cur_phone_number,
cust1.position AS cur_position,
cust1.rep_id_commercial AS cur_rep_id_commercial,
cust1.rep_id_education AS cur_rep_id_education,
cust1.rep_name_commercial AS cur_rep_name_commercial,
cust1.rep_name_education AS cur_rep_name_education,
cust1.store_window AS cur_store_window,
cust1.zip_code AS cur_zip_code,
cust1.rep_email_commercial,
cust1.rep_email_commercial_2,
time1.time_id,
time1.year,
time1.quarter,
time1.month,
time1.week_of_year,
time1.day_of_year,
time1.day_of_month,
time1.day_of_week,
time1.year_quarter,
time1.year_month,
sha2( coalesce(cast(Trans.DATA_DELIVERY_DATE as string),'')
|| coalesce(cast(Trans.KPI as string),'')
|| coalesce(cast(Trans.Kamsoft_program_name as string),'')
|| coalesce(cast(Trans.Kamsoft_program_ID as string),'')
|| coalesce(cast(Trans.Date_purchase as string),'')
|| coalesce(cast(Trans.Expiry_date as string),'')
|| coalesce(cast(Trans.Batch_number as string),'')
|| coalesce(cast(Trans.Distributor as string),'')
|| coalesce(cast(Trans.Sales_type as string),'')
|| coalesce(cast(Trans.Document_ID as string),'')
|| coalesce(cast(Trans.Order_ID as string),'')
|| coalesce(cast(Trans.Sales_time as string),'')
|| coalesce(cast(Trans.Purchase_type as string),'')
|| coalesce(cast(Trans.Date_distributor_sales as string),'')
|| coalesce(cast(Trans.Discount_packet as string),'')
|| coalesce(cast(Trans.Date_start_discount_packet as string),'')
|| coalesce(cast(Trans.Date_end_discount_packet as string),'')
|| coalesce(cast(Trans.Date_order_forward as string),'')
|| coalesce(cast(Trans.Chain_order_ID as string),'')
|| coalesce(cast(Trans.Chain_Customer_name as string),'')
|| coalesce(cast(Trans.Order_status as string),'')
|| coalesce(cast(Trans.Rep_comments as string),'')
|| coalesce(cast(Trans.Distributor_comments as string),'')
|| coalesce(cast(Trans.Internal_comments as string),'')
|| coalesce(cast(Trans.Product_objections as string),'')
|| coalesce(cast(Trans.Additional_info as string),'')
|| coalesce(cast(Trans.TRANSACTION_SOURCE as string),'')
|| coalesce(cast(Trans.transaction_time_id as string),'')
|| coalesce(cast(Trans.transaction_customer_id as string),'')
|| coalesce(cast(Trans.TRANSACTION_CUSTOMER_BK as string),'')
|| coalesce(cast(Trans.transaction_product_id as string),'')
|| coalesce(cast(Trans.TRANSACTION_PRODUCT_BK as string),'')
|| coalesce(cast(Trans.PSDT_AKT_SYNCH as string),'')
|| coalesce(cast(Trans.Date_corrected as string),'')
,256) as f_transaction_key
,current_timestamp() ETLLastModifiedDate

FROM emea_quality_enr_ceec.fact_transactions  Trans
left join emea_quality_enr_ceec.dim_customers cust on cust.customer_id=trans.transaction_customer_id
left join emea_quality_enr_ceec.dim_products prod on prod.product_id=trans.transaction_product_id 
left join emea_quality_enr_ceec.dim_customers cust1 on cust1.customer_bk=trans.transaction_customer_bk 
and cust1.customer_is_valid=true 
left join  emea_quality_enr_ceec.dim_date time1 on cast(time1.time_id as date)=cast(trans.transaction_time_id as date)
where  trans.transaction_customer_bk is not null 
and COALESCE(sku_name,'na') != 'lad' and
(Trans.Sales_type is null or Trans.Sales_type != 'noFisk' )
and (Trans.Purchase_type is null or Trans.Purchase_type != 'MM')
and (Trans.Distributor is null or Trans.Distributor not in ('APTEKA CODZIENNA (Dąbrowa Tarnowska, Rynek 17)', 'APTEKA CODZIENNA (Lipsko, Śniadeckiego 5)','APTEKA CODZIENNA (Lipsko, Zwoleńska 9) ID915173', 'APTEKA CODZIENNA (Przysucha, ul. Radomska 1)', 'APTEKA CODZIENNA (Radom, ul. Mireckiego 14)', 'APTEKA CODZIENNA Agnieszka Stelmach (pl. T. Kościuszki 20)', 'APTEKA CODZIENNA Agnieszka Stelmach (ul. Orzeszkowej 51 C)', 'APTEKA CODZIENNA Agnieszka Stelmach (ul. Romualda 3)', 'APTEKA CODZIENNA Agnieszka Stelmach (ul. Żytnia 1 F)', 'APTEKA CODZIENNA Apteka Rodzinna A.Paliborek M.Ochenduszka Sp.Jawna', 'APTEKA CODZIENNA AT-FARM SP. Z O.O. (pl. Wolności 6)', 'APTEKA CODZIENNA AT-FARM SP. Z O.O. (ul. 1 Maja)', 'APTEKA CODZIENNA AT-FARM SP. Z O.O. (ul. Krasińskiego 20)', 'APTEKA CODZIENNA FARMAZONA SP. Z O.O. (ul. Kopernika 6)', 'APTEKA CODZIENNA FARMAZONA SP. Z O.O. (ul. Paderewskiego 17/2)', 'APTEKA CODZIENNA FARMAZONA SP. Z O.O. (ul. Piastowska 17)', 'APTEKA CODZIENNA FARMAZONA SP. Z O.O. (ul. Pisarka 1 C)', 'APTEKA CODZIENNA FARMAZONA SP. Z O.O. (ul. Staroopatowska 22A)', 'APTEKA CODZIENNA MULTI-AP SP. Z O.O. (os. Ogrody 5 A)',	 'APTEKA CODZIENNA MULTI-AP SP. Z O.O. (ul. Graniczna 18)', 'APTEKA CODZIENNA MULTI-AP SP. Z O.O. (ul. Kilińskiego 15)', 'APTEKA CODZIENNA MULTI-AP SP. Z O.O. (ul. Waryńskiego 32)', 'APTEKA CODZIENNA MULTILEK SP. Z O.O. (al. ks. J. Popiełuszki 40)',	 'APTEKA CODZIENNA MULTILEK SP. Z O.O. (ul. 3 Maja 3)', 'APTEKA CODZIENNA MULTILEK SP. Z O.O. (ul. Wojewódzka 2)', 'APTEKA CODZIENNA MULTILEK SP. Z O.O. (ul. Żytnia 14 A)', 'APTEKA CODZIENNA OSMAN (Chmielnik, 1 Maja 5 )', 'APTEKA CODZIENNA OSMAN (Suków 279A)', 'APTEKA CODZIENNA WOLFARMA (PanaceumŁazy ul.Spółdzielcza 5)', 'APTEKA CODZIENNA WOLFARMA (Przy Rynku Wolbrom ul.Krakowska 2)', 'APTEKA CODZIENNA WOLFARMA (Wolbrom ul.Skalska 9/1 )', 'HURTOWNIA CODZIENNA   FOR AP Robert Stelmach, Agnieszka Stelmach S.C.'))
and (
    (Trans.TRANSACTION_SOURCE in ('S4U-purch', 'S4U-sale', 'S4U-stock') and cust1.external_source = 'Soft4You')
 or (Trans.TRANSACTION_SOURCE in ('BRL', 'Common', 'Curate', 'DOZ', 'Melissa', 'Superpharm', 'WracamDZ', 'Zdrowit') and rtrim(coalesce(cust1.external_source, '')) = '')
 or (Trans.TRANSACTION_SOURCE = 'Kamsoft' and Trans.Kamsoft_program_name = 'PROGRAM PARTNERSKI BAYER 2019' and cust1.external_source = 'Kamsoft (922)')
 or (Trans.TRANSACTION_SOURCE = 'Kamsoft' and Trans.Kamsoft_program_name = 'Program Partnerski Bayer' and cust1.external_source = 'Kamsoft (361)')
 or (Trans.TRANSACTION_SOURCE = 'Kamsoft' and Trans.Kamsoft_program_name = 'BAYER 2024' and cust1.external_source = 'Kamsoft (2637)')
 or (Trans.TRANSACTION_SOURCE = 'Kamsoft' and Trans.Kamsoft_program_name = 'Program Partnerski Bayer Ziko' and cust1.external_source = 'Kamsoft (829)ziko')
 or (Trans.TRANSACTION_SOURCE = 'Farmaprom')
)
and cast(Trans.transaction_time_id as date) >= cast(date_trunc('year',date_add(YEAR, -1, current_date)) as date)
GROUP BY Trans.DATA_DELIVERY_DATE,
Trans.KPI,
Trans.Kamsoft_program_name,
Trans.Kamsoft_program_ID,
Trans.Date_purchase,
Trans.Expiry_date,
Trans.Batch_number,

Trans.Distributor,
Trans.Sales_type,
Trans.Document_ID,
Trans.Order_ID,
Trans.Sales_time,
Trans.Purchase_type,
Trans.Date_distributor_sales,
Trans.Discount_packet,
Trans.Date_start_discount_packet,
Trans.Date_end_discount_packet,
Trans.Date_order_forward,
Trans.Chain_order_ID,
Trans.Chain_Customer_name ,Trans.Order_status,
Trans.Rep_comments,
Trans.Distributor_comments,
Trans.Internal_comments,
Trans.Product_objections,
Trans.Additional_info,
Trans.TRANSACTION_SOURCE,
Trans.transaction_time_id,
Trans.transaction_customer_id,
Trans.TRANSACTION_CUSTOMER_BK,
Trans.transaction_product_id,
Trans.TRANSACTION_PRODUCT_BK,
Trans.PSDT_AKT_SYNCH,
Trans.Discount_percentage,
Trans.ExFactory_price,
Trans.Date_corrected,
cust.adress,
cust.area_commercial,
cust.area_education,
cust.attributes,
cust.behind_counter_exposition,
cust.behind_glass_exposition,
cust.chain_customer_account,
cust.chain_type,
cust.city,
cust.commercial_segment,
cust.contract,
cust.customer_bk,
--cust.customer_change_timestamp,
--cust.customer_change_type,
cust.customer_group,
cust.customer_id,
cust.customer_is_valid,
cust.customer_lad,
cust.customer_source,
cust.customer_valid_from,
cust.customer_valid_to,
cust.dnv_commercial,
cust.dnv_education,
cust.education_segment,
cust.email,
cust.external_source,
cust.group_owner,
cust.group_type,
cust.id_acres,
cust.id_chain_customer,
cust.id_customer,
cust.id_esalesweb,
cust.id_external_reporting,
cust.id_farmaprom,
cust.importance,
cust.iqvia_brick,
cust.is_dermatological,
cust.is_kamsoft,
cust.is_ordering,
cust.is_self_service,
cust.kamsoft_agreement,
cust.last_visit_commercial,
cust.last_visit_education,
cust.name_chain_customer,
cust.nip,
cust.pharmacy_name,
cust.pharmacy_status,
cust.pharmacy_type,
cust.phone_number,
cust.position,
cust.rep_id_commercial,
cust.rep_id_education,
cust.rep_name_commercial,
cust.rep_name_education,
cust.store_window,
cust.zip_code,
prod.active_substance_dosage,
prod.aktualnosc,
prod.attribute,
prod.bazyl,
prod.bloz7,
prod.brand,
prod.brand_group,
prod.category,
prod.ean,
prod.exfactory_price,
prod.fct_tool_name,
prod.form,
prod.is_commercial,
prod.is_contracted,
prod.is_massmarket,
prod.is_msl_list,
prod.key_words,
prod.nr_pozwolenia,
prod.pkwiu,
prod.product_bk,
prod.product_id,
prod.product_is_valid,
prod.product_type,
prod.product_valid_from,
prod.product_valid_to,
prod.sap_id,
prod.sap_name,
prod.sku_name,
prod.sku_short_name,
prod.status,
prod.unit_of_measurement,
prod.units_volume,
prod.vat,
prod.product_source,
cust1.adress,
cust1.area_commercial,
cust1.area_education,
cust1.attributes,
cust1.behind_counter_exposition,
cust1.behind_glass_exposition,
cust1.chain_customer_account,
cust1.chain_type,
cust1.city,
cust1.commercial_segment,
cust1.contract,
cust1.customer_bk,
--cust1.customer_change_timestamp,
--cust1.customer_change_type,
cust1.customer_group,
cust1.customer_id,
cust1.customer_is_valid,
cust1.customer_lad,
cust1.customer_source,
cust1.customer_valid_from,
cust1.customer_valid_to,
cust1.dnv_commercial,
cust1.dnv_education,
cust1.education_segment,
cust1.email,
cust1.external_source,
cust1.group_owner,
cust1.group_type,
cust1.id_acres,
cust1.id_chain_customer,
cust1.id_customer,
cust1.id_esalesweb,
cust1.id_external_reporting,
cust1.id_farmaprom,
cust1.importance,
cust1.iqvia_brick,
cust1.is_dermatological,
cust1.is_kamsoft,
cust1.is_ordering,
cust1.is_self_service,
cust1.kamsoft_agreement,
cust1.last_visit_commercial,
cust1.last_visit_education,
cust1.name_chain_customer,
cust1.nip,
cust1.pharmacy_name,
cust1.pharmacy_status,
cust1.pharmacy_type,
cust1.phone_number,
cust1.position,
cust1.rep_id_commercial,
cust1.rep_id_education,
cust1.rep_name_commercial,
cust1.rep_name_education,
cust1.store_window,
cust1.zip_code,
cust1.rep_email_commercial,
cust1.rep_email_commercial_2,
time1.time_id,
time1.year,
time1.quarter,
time1.month,
time1.week_of_year,
time1.day_of_year,
time1.day_of_month,
time1.day_of_week,
time1.year_quarter,
time1.year_month
)