CREATE TABLE chdaa_prd_lz_emea.emea_raw_lnd_ceec.esalesweb_organization_attribute (
  irda_sys_is_deleted BOOLEAN,
  irda_sys_deleted TIMESTAMP,
  irda_sys_correlation_id STRING,
  value_date TIMESTAMP,
  irda_sys_changed_by STRING,
  product_line_id STRING,
  irda_sys_object_guid STRING,
  object_id DECIMAL(20,0),
  irda_sys_country STRING,
  irda_sys_updated TIMESTAMP,
  userchanged TIMESTAMP,
  value_decimal FLOAT,
  irda_sys_touched TIMESTAMP,
  value_string STRING,
  organization_id STRING,
  createdby STRING,
  sys_source_system STRING,
  changedby STRING,
  irda_sys_created TIMESTAMP,
  client_variant_id DECIMAL(20,0),
  irda_sys_is_dirty BOOLEAN,
  attribute_id STRING,
  changed TIMESTAMP,
  irda_sys_unique_key STRING,
  deleted FLOAT,
  created TIMESTAMP,
  value_selection_id STRING,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://raw@zpdatacoresadpemea.dfs.core.windows.net/landing/ceec/esalesweb_organization_attribute'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '1',
  'delta.minWriterVersion' = '2')