CREATE TABLE chdaa_prd_lz_emea.emea_raw_lnd_ceec.farmaprom_product_brand_current (
  miesieczne_standardowe_zapotrzebowanie_apteki STRING,
  marka_status_liczba STRING,
  rodzaj_produktu_liczba STRING,
  polka_przedstawicielska_liczba STRING,
  produkt_status_liczba STRING,
  ETLIsDeleted BOOLEAN,
  grupa_produktowa_max_data_modyfikacji TIMESTAMP,
  szacunkowa_cena FLOAT,
  ETLChecksum STRING,
  marka STRING,
  marka_status STRING,
  probka_darowizna STRING,
  id_kategoria_produktowa STRING,
  kategoria_produktowa_szeroka STRING,
  postac STRING,
  nazwa_produktu STRING,
  produkt_priorytetowy STRING,
  minimalna_liczba_sztuk_w_zamowieniu STRING,
  liczba_sztuk_w_opakowaniu_zbiorczym STRING,
  mnoznik STRING,
  atc_kod STRING,
  ratujacy_zycie STRING,
  data_dodania TIMESTAMP,
  id_producenta STRING,
  dawka STRING,
  limit_na_klienta_na_rok STRING,
  miesieczne_standardowe_zapotrzebowanie_apteki_liczba STRING,
  polka_przedstawicielska STRING,
  kanal_sprzedazy STRING,
  id_produktu STRING,
  lek_refundowany STRING,
  lek_refundowany_liczba STRING,
  grupa_produktowa STRING,
  rodzaj_produktu STRING,
  kod_produktu STRING,
  ean STRING,
  atc_nazwa STRING,
  id_marka_produktu STRING,
  produkt_priorytetowy_liczba STRING,
  ratujacy_zycie_liczba STRING,
  produkt_status STRING,
  opis STRING,
  bloz STRING,
  kanal_sprzedazy_liczba STRING,
  wielkosc_opakowania STRING,
  dodatkowa_cena FLOAT,
  probka_darowizna_liczba STRING,
  data_modyfikacji TIMESTAMP,
  kategoria_produktowa STRING,
  probka_darowizna_status STRING,
  maksymalny_rabat FLOAT,
  ETLLastModifiedDate TIMESTAMP,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://raw@zpdatacoresadpemea.dfs.core.windows.net/landing/ceec/farmaprom_product_brand_current'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')