CREATE TABLE chdaa_prd_lz_emea.emea_raw_lnd_ceec.esalesweb_account (
  irda_sys_is_deleted BOOLEAN,
  objective STRING,
  expected_value STRING,
  results STRING,
  irda_sys_deleted TIMESTAMP,
  comment_id STRING,
  sub_type STRING,
  proposal STRING,
  type STRING,
  date_started TIMESTAMP,
  needs STRING,
  irda_sys_correlation_id STRING,
  irda_sys_changed_by STRING,
  sales_target_id STRING,
  gps_longitude FLOAT,
  account_id STRING,
  irda_sys_object_guid STRING,
  object_id DECIMAL(20,0),
  irda_sys_country STRING,
  irda_sys_updated TIMESTAMP,
  description STRING,
  status STRING,
  budget FLOAT,
  userchanged TIMESTAMP,
  account_name STRING,
  decision_making_process STRING,
  irda_sys_touched TIMESTAMP,
  sub_status STRING,
  user_id STRING,
  createdby STRING,
  sys_source_system STRING,
  changedby STRING,
  account_no STRING,
  irda_sys_created TIMESTAMP,
  client_variant_id DECIMAL(20,0),
  irda_sys_is_dirty BOOLEAN,
  primary_organization_id STRING,
  changed TIMESTAMP,
  irda_sys_unique_key STRING,
  currency_code STRING,
  deleted FLOAT,
  gps_latitude FLOAT,
  date_ended TIMESTAMP,
  created TIMESTAMP,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://raw@zpdatacoresadpemea.dfs.core.windows.net/landing/ceec/esalesweb_account'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '1',
  'delta.minWriterVersion' = '2')