CREATE TABLE chdaa_prd_lz_emea.emea_raw_lnd_ceec.esalesweb_account_type (
  irda_sys_is_deleted BOOLEAN,
  irda_sys_deleted TIMESTAMP,
  show_date_fields FLOAT,
  irda_sys_correlation_id STRING,
  irda_sys_changed_by STRING,
  team STRING,
  irda_sys_object_guid STRING,
  show_objectives_fields FLOAT,
  object_id DECIMAL(20,0),
  irda_sys_country STRING,
  irda_sys_updated TIMESTAMP,
  status STRING,
  userchanged TIMESTAMP,
  account_type_id STRING,
  business_unit STRING,
  irda_sys_touched TIMESTAMP,
  country_code STRING,
  createdby STRING,
  sys_source_system STRING,
  changedby STRING,
  irda_sys_created TIMESTAMP,
  district STRING,
  show_budget_field FLOAT,
  account_type_name STRING,
  client_variant_id DECIMAL(20,0),
  division STRING,
  irda_sys_is_dirty BOOLEAN,
  region STRING,
  changed TIMESTAMP,
  irda_sys_unique_key STRING,
  deleted FLOAT,
  created TIMESTAMP,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://raw@zpdatacoresadpemea.dfs.core.windows.net/landing/ceec/esalesweb_account_type'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '1',
  'delta.minWriterVersion' = '2')