CREATE TABLE chdaa_prd_lz_emea.emea_raw_lnd_ceec.esalesweb_keyword_value (
  irda_sys_is_deleted BOOLEAN,
  irda_sys_deleted TIMESTAMP,
  locale_code STRING,
  address_supplier_source STRING,
  keyword_value STRING,
  keyword_value_id_l2 STRING,
  irda_sys_correlation_id STRING,
  irda_sys_changed_by STRING,
  keyword_value_id STRING,
  irda_sys_object_guid STRING,
  object_id DECIMAL(20,0),
  irda_sys_country STRING,
  sort_index FLOAT,
  irda_sys_updated TIMESTAMP,
  userchanged TIMESTAMP,
  irda_sys_touched TIMESTAMP,
  valid_until TIMESTAMP,
  address_supplier_no STRING,
  valid_from TIMESTAMP,
  keyword_id STRING,
  createdby STRING,
  sys_source_system STRING,
  changedby STRING,
  irda_sys_created TIMESTAMP,
  client_variant_id DECIMAL(20,0),
  irda_sys_is_dirty BOOLEAN,
  changed TIMESTAMP,
  irda_sys_unique_key STRING,
  deleted FLOAT,
  active FLOAT,
  created TIMESTAMP,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://raw@zpdatacoresadpemea.dfs.core.windows.net/landing/ceec/esalesweb_keyword_value'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '1',
  'delta.minWriterVersion' = '2')