CREATE TABLE chdaa_prd_lz_emea.emea_raw_lnd_ceec.esalesweb_organization_external_system (
  irda_sys_is_deleted BOOLEAN,
  irda_sys_deleted TIMESTAMP,
  irda_sys_correlation_id STRING,
  irda_sys_changed_by STRING,
  organization_info_l4 STRING,
  irda_sys_object_guid STRING,
  object_id DECIMAL(20,0),
  irda_sys_country STRING,
  sort_index FLOAT,
  irda_sys_updated TIMESTAMP,
  userchanged TIMESTAMP,
  organization_info_l2 STRING,
  organization_info_l3 STRING,
  irda_sys_touched TIMESTAMP,
  external_system_no STRING,
  external_system_id STRING,
  organization_id STRING,
  createdby STRING,
  sys_source_system STRING,
  changedby STRING,
  irda_sys_created TIMESTAMP,
  client_variant_id DECIMAL(20,0),
  irda_sys_is_dirty BOOLEAN,
  organization_info STRING,
  changed TIMESTAMP,
  irda_sys_unique_key STRING,
  deleted FLOAT,
  created TIMESTAMP,
  ETLChecksum STRING,
  ETLIsDeleted BOOLEAN,
  ETLLineageID STRING,
  ETLLastModifiedDate TIMESTAMP)
USING delta
LOCATION 'abfss://raw@zpdatacoresadpemea.dfs.core.windows.net/landing/ceec/esalesweb_organization_external_system'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '1',
  'delta.minWriterVersion' = '2')