CREATE VIEW emea_raw_src_bnlx.fico_dim_customer_oriented_responsibility_channel (
  COREC_SID,
  DCOREC_ID COMMENT 'Country-oriented Responsibility Channel ID',
  CUST_ID COMMENT 'Customer ID',
  CS_CHART_ID COMMENT 'Consolidation Chart of Accounts ID',
  CS_ITEM_ID COMMENT 'Item ID',
  PC_ID COMMENT 'Profit Center (Global View) posted ID',
  MATERIAL_ID COMMENT 'Material ID',
  COUNTRY_FD_ID COMMENT 'Country of Final Destination ID',
  PLANT_ID COMMENT 'Plant ID',
  SALES_ORG_ID COMMENT 'Sales Organization ID',
  DISTR_CHAN_ID COMMENT 'Distribution Channel ID',
  DIVISION_ID COMMENT 'Divison ID',
  CUST_CHAN_LOCAL_HL_ID_01_TYPE COMMENT 'Local Customer Channel Hierarchy Level 1 ID Type',
  CUST_CHAN_LOCAL_HL_ID_02_TYPE COMMENT 'Local Customer Channel Hierarchy Level 2 ID Type',
  CUST_CHAN_LOCAL_HL_ID_03_TYPE COMMENT 'Local Customer Channel Hierarchy Level 3 ID Type',
  CUST_CHAN_LOCAL_HL_ID_01 COMMENT 'Local Customer Channel Hierarchy Level ID 1',
  CUST_CHAN_LOCAL_HL_ID_02 COMMENT 'Local Customer Channel Hierarchy Level ID 2',
  CUST_CHAN_LOCAL_HL_ID_03 COMMENT 'Local Customer Channel Hierarchy Level ID 3',
  CUST_CHAN_LOCAL_HL_01 COMMENT 'Local Customer Channel Hierarchy Level 1',
  CUST_CHAN_LOCAL_HL_02 COMMENT 'Local Customer Channel Hierarchy Level 2',
  CUST_CHAN_LOCAL_HL_03 COMMENT 'Local Customer Channel Hierarchy Level 3',
  OPSYS COMMENT 'OPSYS',
  OPTIME COMMENT 'OPTIME',
  OPTYPE COMMENT 'OPTYPE')
WITH SCHEMA COMPENSATION
AS SELECT
        COREC_SID,
        DCOREC_ID,
        CUST_ID,
        CS_CHART_ID,
        CS_ITEM_ID,
        PC_ID,
        MATERIAL_ID,
        COUNTRY_FD_ID,
        PLANT_ID,
        SALES_ORG_ID,
        DISTR_CHAN_ID,
        DIVISION_ID,
        CUST_CHAN_LOCAL_HL_ID_01_TYPE,
        CUST_CHAN_LOCAL_HL_ID_02_TYPE,
        CUST_CHAN_LOCAL_HL_ID_03_TYPE,
        CUST_CHAN_LOCAL_HL_ID_01,
        CUST_CHAN_LOCAL_HL_ID_02,
        CUST_CHAN_LOCAL_HL_ID_03,
        CUST_CHAN_LOCAL_HL_01,
        CUST_CHAN_LOCAL_HL_02,
        CUST_CHAN_LOCAL_HL_03,
        OPSYS,
        OPTIME,
        OPTYPE
    FROM
        chdaa_prd_cda_fico.fico_consume.dim_customer_oriented_responsibility_channel