CREATE VIEW emea_raw_src_bnlx.fico_dim_customer (
  CUST_SID,
  CUST_ID COMMENT 'Customer ID',
  CUST COMMENT 'Customer',
  CUST_CH_ID_01 COMMENT 'Customer Channel ID 1',
  CUST_CH_ID_02 COMMENT 'Customer Channel ID 2',
  CUST_CH_01 COMMENT 'Customer Channel 1',
  CUST_CH_02 COMMENT 'Customer Channel 2',
  CUST_REGION_ID COMMENT 'Customer Region ID',
  CUST_REGION COMMENT 'Customer Region',
  CUST_LEAD_ID COMMENT 'Customer Leading ID',
  CUST_LEAD COMMENT 'Customer Leading',
  CUST_CLASS_ID COMMENT 'Customer Classification ID',
  CUST_CLASS COMMENT 'Customer Classification',
  CUST_DUNS_ID COMMENT 'Customer DUNS Number ID',
  CUST_DUNS COMMENT 'Customer DUNS Number',
  CUST_SORT COMMENT 'Customer Sort Field',
  CUST_INDUSTRY_ID COMMENT 'Customer Industry ID',
  CUST_INDUSTRY COMMENT 'Customer Industry',
  CUST_ACCNT_GRP_ID COMMENT 'Customer Account Group ID',
  CUST_ACCNT_GRP COMMENT 'Customer Account Group',
  CUST_COUNTRY COMMENT 'Customer Country',
  CUST_STREET COMMENT 'Customer Street',
  CUST_CITY COMMENT 'Customer City',
  CUST_POSTAL_CODE COMMENT 'Customer Postal Code',
  OPSYS COMMENT 'OPSYS',
  OPTIME COMMENT 'OPTIME',
  OPTYPE COMMENT 'OPTYPE')
WITH SCHEMA COMPENSATION
AS SELECT
        CUST_SID,
        CUST_ID,
        CUST,
        CUST_CH_ID_01,
        CUST_CH_ID_02,
        CUST_CH_01,
        CUST_CH_02,
        CUST_REGION_ID,
        CUST_REGION,
        CUST_LEAD_ID,
        CUST_LEAD,
        CUST_CLASS_ID,
        CUST_CLASS,
        CUST_DUNS_ID,
        CUST_DUNS,
        CUST_SORT,
        CUST_INDUSTRY_ID,
        CUST_INDUSTRY,
        CUST_ACCNT_GRP_ID,
        CUST_ACCNT_GRP,
        CUST_COUNTRY,
        CUST_STREET,
        CUST_CITY,
        CUST_POSTAL_CODE,
        OPSYS,
        OPTIME,
        OPTYPE
    FROM
        chdaa_prd_cda_fico.fico_consume.dim_customer