CREATE VIEW emea_raw_src_bnlx.vw_nl_dim_product (
  ETLLineageID,
  ETLChecksum,
  ETLIsDeleted,
  ETLLastModifiedDate,
  product_agg_lvl1_code,
  product_stub_id,
  product_ean_descr,
  product_agg_lvl6_descr,
  product_agg_lvl4_code,
  product_agg_lvl3_code,
  product_agg_lvl2_descr,
  file_name,
  product_level,
  product_agg_lvl6_code,
  load_id,
  product_agg_lvl7_code,
  manufacturer,
  product_agg_lvl8_descr,
  product_agg_lvl2_code,
  product_identifier_code,
  product_agg_lvl5_code,
  product_agg_lvl8_code,
  product_agg_lvl3_descr,
  content,
  product_ean_code,
  product_agg_lvl4_descr,
  product_agg_lvl5_descr,
  d_product_code,
  product_agg_lvl7_descr,
  iri_product_description,
  product_entry_type,
  product_agg_lvl1_descr)
WITH SCHEMA BINDING
AS (SELECT * FROM  chdaa_prd_cda_mkt.mkt_consume_emea.nl_dim_product)