CREATE VIEW emea_raw_src_bnlx.fico_dim_sales_customer (
  SALES_CUST_SID,
  SALES_CUST_ID COMMENT 'Sales Customer ID',
  SALES_CUST COMMENT 'Sales Customer',
  DIVISION_ID COMMENT 'Division ID',
  DIVISION COMMENT 'Division',
  DISTR_CHAN_ID COMMENT 'Distribution Chain ID',
  DISTR_CHAIN COMMENT 'Distribution Chain',
  SALES_ORG_ID COMMENT 'Sales Organization ID',
  SALES_ORG COMMENT 'Sales Organization',
  CUST_GRP_ID COMMENT 'Customer Group ID',
  CUST_GRP COMMENT 'Customer Group',
  CUST_GRP_HL_ID_01 COMMENT 'Customer Group ID Hierarchy Level 1',
  CUST_GRP_HL_ID_02 COMMENT 'Customer Group ID Hierarchy Level 2',
  CUST_GRP_HL_ID_03 COMMENT 'Customer Group ID Hierarchy Level 3',
  CUST_GRP_HL_ID_04 COMMENT 'Customer Group ID Hierarchy Level 4',
  CUST_GRP_HL_ID_05 COMMENT 'Customer Group ID Hierarchy Level 5',
  CUST_GRP_HL_01 COMMENT 'Customer Group Hierarchy Level 1',
  CUST_GRP_HL_02 COMMENT 'Customer Group Hierarchy Level 2',
  CUST_GRP_HL_03 COMMENT 'Customer Group Hierarchy Level 3',
  CUST_GRP_HL_04 COMMENT 'Customer Group Hierarchy Level 4',
  CUST_GRP_HL_05 COMMENT 'Customer Group Hierarchy Level 5',
  CUST_COUNTRY_CODE_ID COMMENT 'Customer Country Specific Code ID',
  CUST_COUNTRY_CODE COMMENT 'Customer Country Specific Code',
  PRICE_GROUP_ID COMMENT 'Price Group ID',
  PRICE_GROUP COMMENT 'Price Group',
  OPSYS COMMENT 'OPSYS',
  OPTIME COMMENT 'OPTIME',
  OPTYPE COMMENT 'OPTYPE')
WITH SCHEMA COMPENSATION
AS SELECT
        SALES_CUST_SID,
        SALES_CUST_ID,
        SALES_CUST,
        DIVISION_ID,
        DIVISION,
        DISTR_CHAN_ID,
        DISTR_CHAIN,
        SALES_ORG_ID,
        SALES_ORG,
        CUST_GRP_ID,
        CUST_GRP,
        CUST_GRP_HL_ID_01,
        CUST_GRP_HL_ID_02,
        CUST_GRP_HL_ID_03,
        CUST_GRP_HL_ID_04,
        CUST_GRP_HL_ID_05,
        CUST_GRP_HL_01,
        CUST_GRP_HL_02,
        CUST_GRP_HL_03,
        CUST_GRP_HL_04,
        CUST_GRP_HL_05,
        CUST_COUNTRY_CODE_ID,
        CUST_COUNTRY_CODE,
        PRICE_GROUP_ID,
        PRICE_GROUP,
        OPSYS,
        OPTIME,
        OPTYPE
    FROM
        chdaa_prd_cda_fico.fico_consume.dim_sales_customer