CREATE VIEW emea_raw_src_bnlx.fico_dim_business_responsibility (
  RESPO_SID,
  COMPANY_CODE_ID COMMENT 'Company Code ID',
  CO_AREA_ID COMMENT 'Controlling Area ID',
  CS_CHART_ID COMMENT 'Consolidation Chart of Accounts ID',
  CS_ITEM_ID COMMENT 'Item ID',
  CS_ITEM_SUB_ID COMMENT 'Item Subitem ID',
  CS_ITEM_SUB_CAT_ID COMMENT 'Item Subitem Category ID',
  DISTR_CHAN_ID COMMENT 'Distribution Channel ID',
  MATERIAL_ID COMMENT 'Material ID',
  PLANT_ID COMMENT 'Plant ID',
  SALES_ORG_ID COMMENT 'Sales Organization ID',
  SEND_CCTR_ID COMMENT 'Sending Cost Center ID',
  COUNTRY_FD_ID COMMENT 'Country of Final Destination ID',
  PC_ID COMMENT 'Profit Center (Global View), posted ID',
  RESPO_ID COMMENT 'Business Responsibility ID',
  RESPO_HL_ID_01 COMMENT 'Business Responsibility Level ID 1',
  RESPO_HL_ID_02 COMMENT 'Business Responsibility Level ID 2',
  RESPO_HL_01 COMMENT 'Business Responsibility Level 1',
  RESPO_HL_02 COMMENT 'Business Responsibility Level 2',
  BSV_HL_ID_01 COMMENT 'Business Steering View Hierarchy Level ID 01',
  BSV_HL_ID_02 COMMENT 'Business Steering View Hierarchy Level ID 02',
  BSV_HL_ID_03 COMMENT 'Business Steering View Hierarchy Level ID 03',
  BSV_HL_ID_04 COMMENT 'Business Steering View Hierarchy Level ID 04',
  BSV_HL_ID_05 COMMENT 'Business Steering View Hierarchy Level ID 05',
  BSV_HL_ID_06 COMMENT 'Business Steering View Hierarchy Level ID 06',
  BSV_HL_ID_07 COMMENT 'Business Steering View Hierarchy Level ID 07',
  BSV_HL_ID_08 COMMENT 'Business Steering View Hierarchy Level ID 08',
  BSV_HL_ID_09 COMMENT 'Business Steering View Hierarchy Level ID 09',
  BSV_HL_ID_10 COMMENT 'Business Steering View Hierarchy Level ID 10',
  BSV_HL_01 COMMENT 'Business Steering View Hierarchy Level 01',
  BSV_HL_02 COMMENT 'Business Steering View Hierarchy Level 02',
  BSV_HL_03 COMMENT 'Business Steering View Hierarchy Level 03',
  BSV_HL_04 COMMENT 'Business Steering View Hierarchy Level 04',
  BSV_HL_05 COMMENT 'Business Steering View Hierarchy Level 05',
  BSV_HL_06 COMMENT 'Business Steering View Hierarchy Level 06',
  BSV_HL_07 COMMENT 'Business Steering View Hierarchy Level 07',
  BSV_HL_08 COMMENT 'Business Steering View Hierarchy Level 08',
  BSV_HL_09 COMMENT 'Business Steering View Hierarchy Level 09',
  BSV_HL_10 COMMENT 'Business Steering View Hierarchy Level 10',
  BG_CV_ID COMMENT 'Business Group ID',
  BG_CV COMMENT 'Business Group',
  SG_CV_ID COMMENT 'Sub Group ID',
  SG_CV COMMENT 'Sub Group',
  SBE_CV_ID COMMENT 'Strategic Business Entity ID',
  SBE_CV COMMENT 'Strategic Business Entity',
  RU_CV_ID COMMENT 'Reporting Unit ID',
  RU_CV COMMENT 'Reporting Unit',
  PC_CV_ID COMMENT 'Profit Center (Controlling View) ID',
  PC_CV COMMENT 'Profit Center (Controlling View)',
  CAT_CH_ID COMMENT 'Category ID',
  CAT_CH COMMENT 'Category',
  MSRC_ID COMMENT 'Merger Source ID',
  MSRC COMMENT 'Merger Source',
  BSV_ID COMMENT 'Business Steering View ID',
  BSV COMMENT 'Business Steering View',
  LOC_BU_ID COMMENT 'Local Business Unit ID',
  LOC_BU COMMENT 'Local Business Unit',
  PS_RESPO_SID,
  PS_SITE_ID COMMENT 'Production Site ID',
  PS_SITE COMMENT 'Production Site',
  BRAND_ID COMMENT 'Brand ID',
  BRAND COMMENT 'Brand',
  BRAND_GROUPING_ID COMMENT 'Brand Grouping ID',
  BRAND_GROUPING COMMENT 'BRAND_GROUPING',
  SUB_BRAND_ID COMMENT 'Sub Brand / Brand Family ID',
  SUB_BRAND COMMENT 'Sub Brand / Brand Family',
  OPSYS COMMENT 'OPSYS',
  OPTIME COMMENT 'OPTIME',
  OPTYPE COMMENT 'OPTYPE')
WITH SCHEMA COMPENSATION
AS SELECT
        RESPO_SID,
        COMPANY_CODE_ID,
        CO_AREA_ID,
        CS_CHART_ID,
        CS_ITEM_ID,
        CS_ITEM_SUB_ID,
        CS_ITEM_SUB_CAT_ID,
        DISTR_CHAN_ID,
        MATERIAL_ID,
        PLANT_ID,
        SALES_ORG_ID,
        SEND_CCTR_ID,
        COUNTRY_FD_ID,
        PC_ID,
        RESPO_ID,
        RESPO_HL_ID_01,
        RESPO_HL_ID_02,
        RESPO_HL_01,
        RESPO_HL_02,
        BSV_HL_ID_01,
        BSV_HL_ID_02,
        BSV_HL_ID_03,
        BSV_HL_ID_04,
        BSV_HL_ID_05,
        BSV_HL_ID_06,
        BSV_HL_ID_07,
        BSV_HL_ID_08,
        BSV_HL_ID_09,
        BSV_HL_ID_10,
        BSV_HL_01,
        BSV_HL_02,
        BSV_HL_03,
        BSV_HL_04,
        BSV_HL_05,
        BSV_HL_06,
        BSV_HL_07,
        BSV_HL_08,
        BSV_HL_09,
        BSV_HL_10,
        BG_CV_ID,
        BG_CV,
        SG_CV_ID,
        SG_CV,
        SBE_CV_ID,
        SBE_CV,
        RU_CV_ID,
        RU_CV,
        PC_CV_ID,
        PC_CV,
        CAT_CH_ID,
        CAT_CH,
        MSRC_ID,
        MSRC,
        BSV_ID,
        BSV,
        LOC_BU_ID,
        LOC_BU,
        PS_RESPO_SID,
        PS_SITE_ID,
        PS_SITE,
        BRAND_ID,
        BRAND,
        BRAND_GROUPING_ID,
        BRAND_GROUPING,
        SUB_BRAND_ID,
        SUB_BRAND,
        OPSYS,
        OPTIME,
        OPTYPE
    FROM
        chdaa_prd_cda_fico.fico_consume.dim_business_responsibility