CREATE VIEW emea_raw_src_bnlx.fico_dim_partner_company_code (
  PARTNER_COMPANY_CODE_SID,
  PARTNER_COMPANY_CODE_ID COMMENT 'Company Code ID',
  PARTNER_COMPANY_CODE COMMENT 'Company Code',
  PARTNER_COMPANY_ID COMMENT 'Company ID',
  PARTNER_COMPANY COMMENT 'Company',
  COUNTRY_ID COMMENT 'Country ID',
  PARTNER_COMPANY_CODE_CUR COMMENT 'Company Code Currency',
  PARTNER_COMPANY_CONS_UNIT_ID COMMENT 'Company Consolidation Unit ID',
  PARTNER_COMPANY_CONS_UNIT COMMENT 'Company Consolidation Unit',
  PARTNER_COMPANY_AB_STATUS_ID COMMENT 'Company AB Status ID',
  PARTNER_COMPANY_AB_STATUS COMMENT 'Company AB Status',
  PARTNER_COMPANY_SUPPLY_CHAIN_ROLE_ID COMMENT 'Company Supply Chain Role ID',
  PARTNER_COMPANY_SUPPLY_CHAIN_ROLE COMMENT 'Company Supply Chain Role',
  COUNTRY_GROUP_ID COMMENT 'Country Group ID',
  OPSYS COMMENT 'OPSYS',
  OPTIME COMMENT 'OPTIME',
  OPTYPE COMMENT 'OPTYPE')
WITH SCHEMA COMPENSATION
AS SELECT
        PARTNER_COMPANY_CODE_SID,
        PARTNER_COMPANY_CODE_ID,
        PARTNER_COMPANY_CODE,
        PARTNER_COMPANY_ID,
        PARTNER_COMPANY,
        COUNTRY_ID,
        PARTNER_COMPANY_CODE_CUR,
        PARTNER_COMPANY_CONS_UNIT_ID,
        PARTNER_COMPANY_CONS_UNIT,
        PARTNER_COMPANY_AB_STATUS_ID,
        PARTNER_COMPANY_AB_STATUS,
        PARTNER_COMPANY_SUPPLY_CHAIN_ROLE_ID,
        PARTNER_COMPANY_SUPPLY_CHAIN_ROLE,
        COUNTRY_GROUP_ID,
        OPSYS,
        OPTIME,
        OPTYPE
    FROM
        chdaa_prd_cda_fico.fico_consume.dim_partner_company_code