CREATE VIEW emea_raw_src_bnlx.fico_dim_sold_to (
  SOLD_TO_SID,
  SOLD_TO_ID COMMENT 'Customer ID',
  SOLD_TO COMMENT 'Customer',
  SOLD_TO_CH_ID_01 COMMENT 'Customer Channel ID 1',
  SOLD_TO_CH_ID_02 COMMENT 'Customer Channel ID 2',
  SOLD_TO_CH_01 COMMENT 'Customer Channel 1',
  SOLD_TO_CH_02 COMMENT 'Customer Channel 2',
  SOLD_TO_CLASS_ID COMMENT 'Customer Classification ID',
  SOLD_TO_CLASS COMMENT 'Customer Classification',
  SOLD_TO_ACCNT_GRP_ID COMMENT 'Customer Account Group ID',
  SOLD_TO_ACCNT_GRP COMMENT 'Customer Account Group',
  SOLD_TO_INDUSTRY_ID COMMENT 'Customer Industry ID',
  SOLD_TO_INDUSTRY COMMENT 'Customer Industry',
  SOLD_TO_REGION_ID COMMENT 'Customer Region ID',
  SOLD_TO_REGION COMMENT 'Customer Region',
  SOLD_TO_COUNTRY_ID COMMENT 'Customer Country ID',
  SOLD_TO_COUNTRY COMMENT 'Customer Country',
  SOLD_TO_POSTAL_CODE COMMENT 'Customer Postal Code',
  SOLD_TO_CITY COMMENT 'Customer City',
  SOLD_TO_STREET COMMENT 'Customer Street',
  OPSYS COMMENT 'OPSYS',
  OPTIME COMMENT 'OPTIME',
  OPTYPE COMMENT 'OPTYPE')
WITH SCHEMA COMPENSATION
AS SELECT
        SOLD_TO_SID,
        SOLD_TO_ID,
        SOLD_TO,
        SOLD_TO_CH_ID_01,
        SOLD_TO_CH_ID_02,
        SOLD_TO_CH_01,
        SOLD_TO_CH_02,
        SOLD_TO_CLASS_ID,
        SOLD_TO_CLASS,
        SOLD_TO_ACCNT_GRP_ID,
        SOLD_TO_ACCNT_GRP,
        SOLD_TO_INDUSTRY_ID,
        SOLD_TO_INDUSTRY,
        SOLD_TO_REGION_ID,
        SOLD_TO_REGION,
        SOLD_TO_COUNTRY_ID,
        SOLD_TO_COUNTRY,
        SOLD_TO_POSTAL_CODE,
        SOLD_TO_CITY,
        SOLD_TO_STREET,
        OPSYS,
        OPTIME,
        OPTYPE
    FROM
        chdaa_prd_cda_fico.fico_consume.dim_sold_to