CREATE VIEW emea_raw_src_bnlx.fico_dim_material (
  MATERIAL_SID,
  MATERIAL_ID COMMENT 'Material ID',
  MATERIAL COMMENT 'Material',
  MATERIAL_TYPE_ID COMMENT 'Material Type ID',
  PRODH_ID COMMENT 'Production Hiearchy ID',
  PRODH COMMENT 'Production Hierarchy',
  MATERIAL_TYPE COMMENT 'Material Type',
  PRODH_HL_ID_01 COMMENT 'Product Hierarchy Level ID 1',
  PRODH_HL_ID_02 COMMENT 'Product Hierarchy Level ID 2',
  PRODH_HL_ID_03 COMMENT 'Product Hierarchy Level ID 3',
  PRODH_HL_ID_04 COMMENT 'Product Hierarchy Level ID 4',
  PRODH_HL_ID_05 COMMENT 'Product Hierarchy Level ID 5',
  PRODH_HL_ID_06 COMMENT 'Product Hierarchy Level ID 6',
  PRODH_HL_01 COMMENT 'Product Hierarchy Level 1',
  PRODH_HL_02 COMMENT 'Product Hierarchy Level 2',
  PRODH_HL_03 COMMENT 'Product Hierarchy Level 3',
  PRODH_HL_04 COMMENT 'Product Hierarchy Level 4',
  PRODH_HL_05 COMMENT 'Product Hierarchy Level 5',
  PRODH_HL_06 COMMENT 'Product Hierarchy Level 6',
  BRAND_ID COMMENT 'Brand ID',
  BRAND COMMENT 'Brand',
  DIVISON COMMENT 'Division',
  DIVISION_ID COMMENT 'Division ID',
  SUB_BRAND_ID COMMENT 'Sub Brand / Brand Family ID',
  SUB_BRAND COMMENT 'Sub Brand / Brand Family',
  BRAND_FAMILY_ID COMMENT 'Sub Brand / Brand Family ID',
  BRAND_FAMILY COMMENT 'Sub Brand / Brand Family',
  MATERIAL_CLASS_OF_GOODS_ID COMMENT 'Material Class of Goods ID',
  MATERIAL_CLASS_OF_GOODS COMMENT 'Material Class of Goods',
  EAN_UPC_ID COMMENT 'European Article Number / Universal Product Code',
  SPG_ID COMMENT 'Sales Product Group ID',
  UVP_ID COMMENT 'Unpacked Goods (UVP) ID',
  MATERIAL_GROUP_ID COMMENT 'Material Group ID',
  MATERIAL_GROUP COMMENT 'Material Group',
  FGPS_ID COMMENT 'Finished Good Pack Size ID',
  FGPSUOM_ID COMMENT 'Finished Good Pack Size Base Unit of Measure ID',
  COMBIPACK_FLAG COMMENT 'Combipack Flag',
  COMBIPACK COMMENT 'Combipack Description',
  PACK_TYPE COMMENT 'Primary Pack Type',
  TRIANGULATION_FLAG COMMENT 'Triangulated',
  PRODUCTION_SITE COMMENT 'Production Site',
  PACKAGING_SITE COMMENT 'Packaging Site',
  FORMULATION_CONCAT_ID COMMENT 'Formulation (Concatenated) ID',
  FORMULATION_CONCAT COMMENT 'Formulation (Concatenated)',
  MATERIAL_LCP COMMENT 'Material Life Cycle Plase',
  EXT_MATERIAL_GROUP COMMENT 'External Material Group',
  GTIN_1 COMMENT 'GTIN Alternative 1',
  GTIN_1_AUOM_ID_1 COMMENT 'GTIN Alternative 1 Unit of Measure ID 1',
  GTIN_1_AUOM_1 COMMENT 'GTIN Alternative 1 Unit of Measure 1',
  GTIN_1_AUOM_ID_2 COMMENT 'GTIN Alternative 1 Unit of Measure ID 2',
  GTIN_1_AUOM_2 COMMENT 'GTIN Alternative 1 Unit of Measure 2',
  GTIN_2 COMMENT 'GTIN Alternative 2',
  GTIN_2_AUOM_ID_1 COMMENT 'GTIN Alternative 2 Unit of Measure ID 1',
  GTIN_2_AUOM_1 COMMENT 'GTIN Alternative 2 Unit of Measure 1',
  GTIN_2_AUOM_ID_2 COMMENT 'GTIN Alternative 2 Unit of Measure ID 2',
  GTIN_2_AUOM_2 COMMENT 'GTIN Alternative 2 Unit of Measure 2',
  STORAGE_CONDITION_ID COMMENT 'Storage Condition ID',
  STORAGE_CONDITION COMMENT 'Storage Condition',
  EAN_UPC_CATEGORY_ID COMMENT 'European Article Number / Universal Product Code Category',
  INDUSTRY_SECTOR COMMENT 'Industry Sector',
  SOURCE_SYSTEM_ID COMMENT 'Source System ID',
  MATERIAL_CATEGORY_ID COMMENT 'Material Category ID',
  MATERIAL_CATEGORY COMMENT 'Material Category',
  BRAND_GROUPING_ID COMMENT 'Brand Grouping ID',
  BRAND_GROUPING COMMENT 'Brand Grouping',
  BRAND_SUFFIX_ID COMMENT 'Brand Suffix ID',
  BRAND_SUFFIX COMMENT 'Brand Suffix',
  CH_ORG_UNIT_ID_01 COMMENT 'Organization Unit ID 1',
  CH_ORG_UNIT_ID_02 COMMENT 'Organization Unit ID 2',
  CH_ORG_UNIT_ID_03 COMMENT 'Organization Unit ID 3',
  CH_ORG_UNIT_ID_04 COMMENT 'Organization Unit ID 4',
  CH_ORG_UNIT_ID_05 COMMENT 'Organization Unit ID 5',
  CH_ORG_UNIT_01 COMMENT 'Organization Unit 1',
  CH_ORG_UNIT_02 COMMENT 'Organization Unit 2',
  CH_ORG_UNIT_03 COMMENT 'Organization Unit 3',
  CH_ORG_UNIT_04 COMMENT 'Organization Unit 4',
  CH_ORG_UNIT_05 COMMENT 'Organization Unit 5',
  SPG COMMENT 'Sales Product Group',
  UVP COMMENT 'Unpacked Goods (UVP)',
  MATERIAL_BRAND_CLASS_ID COMMENT 'Material Brand Class ID',
  MATERIAL_BRAND_CLASS COMMENT 'Material Brand Class',
  MATERIAL_COUNTRY_CLASS_ID COMMENT 'Material Country Class ID',
  MATERIAL_COUNTRY_CLASS COMMENT 'Material Country Class',
  MATERIAL_PRIORIZATION_ID COMMENT 'Material Priorization ID',
  MATERIAL_PRIORIZATION COMMENT 'Material Priorization',
  MATERIAL_BASE_UOM_ID COMMENT 'Material Base Unit of Measure ID',
  MATERIAL_BASE_UOM COMMENT 'Material Base Unit of Measure',
  MATERIAL_VENDOR_ID COMMENT 'Material Vendor ID',
  MATERIAL_VENDOR COMMENT 'Material Vendor',
  MATERIAL_BUSINESS_AREA_ID COMMENT 'Material Business Area ID',
  MATERIAL_BUSINESS_AREA COMMENT 'Material Business Area',
  MATERIAL_STATUS_ID COMMENT 'Material Status ID',
  MATERIAL_STATUS COMMENT 'Material Status',
  MATERIAL_DEL_FLAG COMMENT 'Material Deletion Flag',
  MANUFACTURING_RESPONSIBILITY_ID COMMENT 'Manufacturing Responsibility ID',
  MANUFACTURING_RESPONSIBILITY COMMENT 'Manufacturing Responsibility',
  SUPPLY_RESPONSIBILITY_LEVEL_2_ID COMMENT 'Supply Responsibility Level 2 ID',
  SUPPLY_RESPONSIBILITY_LEVEL_2 COMMENT 'Supply Responsibility Level 2',
  PZN COMMENT 'Pharmaceutical central number (PZN)',
  FORMULATION_ID COMMENT 'Formulation ID',
  FORMULATION COMMENT 'Formulation',
  FORMULATION_DEV_CENTER COMMENT 'Formulation Development Center',
  FORMULATION_DOSSIER_TYPE COMMENT 'Formulation Dossier Type',
  FORMULATION_FLAVOUR COMMENT 'Formulation Flavour',
  FORMULATION_GALENICAL_FORM COMMENT 'Formulation Galenical Form',
  FORMULATION_LCP COMMENT 'Formulation Life Cycle Phase',
  FORMULATION_SBU_CATEGORY COMMENT 'Formulation SBU Category',
  FORMULATION_QUANTITY COMMENT 'Formulation Quantity',
  FORMULATION_UOM COMMENT 'Formulation Unit of Measure',
  GLOBAL_PRODUCT_SID,
  PRODUCTION_SITE_TYPE,
  OPSYS COMMENT 'OPSYS',
  OPTIME COMMENT 'OPTIME',
  OPTYPE COMMENT 'OPTYPE')
WITH SCHEMA COMPENSATION
AS SELECT
        MATERIAL_SID,
        MATERIAL_ID,
        MATERIAL,
        MATERIAL_TYPE_ID,
        PRODH_ID,
        PRODH,
        MATERIAL_TYPE,
        PRODH_HL_ID_01,
        PRODH_HL_ID_02,
        PRODH_HL_ID_03,
        PRODH_HL_ID_04,
        PRODH_HL_ID_05,
        PRODH_HL_ID_06,
        PRODH_HL_01,
        PRODH_HL_02,
        PRODH_HL_03,
        PRODH_HL_04,
        PRODH_HL_05,
        PRODH_HL_06,
        BRAND_ID,
        BRAND,
        DIVISON,
        DIVISION_ID,
        SUB_BRAND_ID,
        SUB_BRAND,
        BRAND_FAMILY_ID,
        BRAND_FAMILY,
        MATERIAL_CLASS_OF_GOODS_ID,
        MATERIAL_CLASS_OF_GOODS,
        EAN_UPC_ID,
        SPG_ID,
        UVP_ID,
        MATERIAL_GROUP_ID,
        MATERIAL_GROUP,
        FGPS_ID,
        FGPSUOM_ID,
        COMBIPACK_FLAG,
        COMBIPACK,
        PACK_TYPE,
        TRIANGULATION_FLAG,
        PRODUCTION_SITE,
        PACKAGING_SITE,
        FORMULATION_CONCAT_ID,
        FORMULATION_CONCAT,
        MATERIAL_LCP,
        EXT_MATERIAL_GROUP,
        GTIN_1,
        GTIN_1_AUOM_ID_1,
        GTIN_1_AUOM_1,
        GTIN_1_AUOM_ID_2,
        GTIN_1_AUOM_2,
        GTIN_2,
        GTIN_2_AUOM_ID_1,
        GTIN_2_AUOM_1,
        GTIN_2_AUOM_ID_2,
        GTIN_2_AUOM_2,
        STORAGE_CONDITION_ID,
        STORAGE_CONDITION,
        EAN_UPC_CATEGORY_ID,
        INDUSTRY_SECTOR,
        SOURCE_SYSTEM_ID,
        MATERIAL_CATEGORY_ID,
        MATERIAL_CATEGORY,
        BRAND_GROUPING_ID,
        BRAND_GROUPING,
        BRAND_SUFFIX_ID,
        BRAND_SUFFIX,
        CH_ORG_UNIT_ID_01,
        CH_ORG_UNIT_ID_02,
        CH_ORG_UNIT_ID_03,
        CH_ORG_UNIT_ID_04,
        CH_ORG_UNIT_ID_05,
        CH_ORG_UNIT_01,
        CH_ORG_UNIT_02,
        CH_ORG_UNIT_03,
        CH_ORG_UNIT_04,
        CH_ORG_UNIT_05,
        SPG,
        UVP,
        MATERIAL_BRAND_CLASS_ID,
        MATERIAL_BRAND_CLASS,
        MATERIAL_COUNTRY_CLASS_ID,
        MATERIAL_COUNTRY_CLASS,
        MATERIAL_PRIORIZATION_ID,
        MATERIAL_PRIORIZATION,
        MATERIAL_BASE_UOM_ID,
        MATERIAL_BASE_UOM,
        MATERIAL_VENDOR_ID,
        MATERIAL_VENDOR,
        MATERIAL_BUSINESS_AREA_ID,
        MATERIAL_BUSINESS_AREA,
        MATERIAL_STATUS_ID,
        MATERIAL_STATUS,
        MATERIAL_DEL_FLAG,
        MANUFACTURING_RESPONSIBILITY_ID,
        MANUFACTURING_RESPONSIBILITY,
        SUPPLY_RESPONSIBILITY_LEVEL_2_ID,
        SUPPLY_RESPONSIBILITY_LEVEL_2,
        PZN,
        FORMULATION_ID,
        FORMULATION,
        FORMULATION_DEV_CENTER,
        FORMULATION_DOSSIER_TYPE,
        FORMULATION_FLAVOUR,
        FORMULATION_GALENICAL_FORM,
        FORMULATION_LCP,
        FORMULATION_SBU_CATEGORY,
        FORMULATION_QUANTITY,
        FORMULATION_UOM,
        GLOBAL_PRODUCT_SID,
        PRODUCTION_SITE_TYPE,
        OPSYS,
        OPTIME,
        OPTYPE
    FROM
        chdaa_prd_cda_fico.fico_consume.dim_material