CREATE VIEW emea_raw_src_bnlx.fico_dim_date (
  DATE_SID COMMENT 'Date SID',
  DATE_ID COMMENT 'Date ID',
  DATE COMMENT 'Date',
  YEAR COMMENT 'Year',
  MONTH COMMENT 'Month',
  QUARTER COMMENT 'Quarter',
  QUARTER_NAME COMMENT 'Quarter Name',
  QUARTER_OF_YEAR_NAME COMMENT 'Quarter of Year Name',
  QUARTER_OF_YEAR COMMENT 'Quarter of Year',
  MONTH_NAME COMMENT 'Month Name',
  MONTH_NAME_SHORT COMMENT 'Month Name Short',
  MONTH_OF_YEAR_NAME COMMENT 'Month of Year Name',
  MONTH_OF_YEAR COMMENT 'Month of Year',
  WEEK_ISO COMMENT 'ISO Week',
  DAY_OF_WEEK_ISO COMMENT 'Day of Week ISO',
  DAY_OF_WEEK_SUN COMMENT 'Day of Week Sunday',
  DAY_NAME COMMENT 'Day Name',
  DAY_NAME_SHORT COMMENT 'Day Name Short',
  DAY_OF_MONTH COMMENT 'Day of Month',
  OPSYS COMMENT 'OPSYS',
  OPTIME COMMENT 'OPTIME',
  OPTYPE COMMENT 'OPTYPE')
WITH SCHEMA COMPENSATION
AS SELECT
        DATE_SID,
        DATE_ID,
        DATE,
        YEAR,
        MONTH,
        QUARTER,
        QUARTER_NAME,
        QUARTER_OF_YEAR_NAME,
        QUARTER_OF_YEAR,
        MONTH_NAME,
        MONTH_NAME_SHORT,
        MONTH_OF_YEAR_NAME,
        MONTH_OF_YEAR,
        WEEK_ISO,
        DAY_OF_WEEK_ISO,
        DAY_OF_WEEK_SUN,
        DAY_NAME,
        DAY_NAME_SHORT,
        DAY_OF_MONTH,
        OPSYS,
        OPTIME,
        OPTYPE
    FROM
        chdaa_prd_cda_fico.fico_consume.dim_date