CREATE TABLE chdaa_prd_lz_emea.emea_curated_disc_ceec.dim_customers (
  ETLLineageID STRING,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  iqvia_brick STRING,
  position STRING,
  chain_type STRING,
  kamsoft_agreement STRING,
  group_type STRING,
  id_customer STRING,
  id_chain_customer STRING,
  behind_glass_exposition STRING,
  rep_email_commercial STRING,
  id_acres STRING,
  rep_id_education STRING,
  behind_counter_exposition STRING,
  id_external_reporting STRING,
  rep_email_commercial_2 STRING,
  customer_is_valid BOOLEAN,
  id_esalesweb STRING,
  customer_valid_from TIMESTAMP,
  city STRING,
  nip STRING,
  etlchecksumscd1 STRING,
  id_farmaprom STRING,
  dnv_education STRING,
  zip_code STRING,
  area_commercial STRING,
  customer_change_type STRING,
  pharmacy_name STRING,
  area_education STRING,
  lastmodifieddate DATE,
  customer_lad STRING,
  pharmacy_type STRING,
  customer_valid_to TIMESTAMP,
  chain_customer_account STRING,
  name_chain_customer STRING,
  importance STRING,
  group_owner STRING,
  commercial_segment STRING,
  rep_name_education STRING,
  adress STRING,
  education_segment STRING,
  external_source STRING,
  attributes STRING,
  customer_id STRING,
  email STRING,
  customer_group STRING,
  contract STRING,
  dnv_commercial STRING,
  pharmacy_status STRING,
  rep_id_commercial STRING,
  is_dermatological STRING,
  is_self_service STRING,
  is_kamsoft STRING,
  last_visit_commercial DATE,
  customer_bk STRING,
  phone_number STRING,
  store_window STRING,
  etlchecksumscd2 STRING,
  customer_change_timestamp TIMESTAMP,
  rep_name_commercial STRING,
  is_ordering STRING,
  customer_source STRING,
  last_visit_education DATE)
USING delta
LOCATION 'abfss://curated@zpdatacoresadpemea.dfs.core.windows.net/discovery/ceec/dim_customers'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 7 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')