CREATE TABLE chdaa_prd_lz_emea.emea_curated_disc_ceec.fact_transactions_bkp_12_11_2025 (
  document_id STRING,
  date_order_forward DATE,
  kpi STRING,
  discount_percentage DECIMAL(18,2),
  distributor_comments STRING,
  exfactory_price DECIMAL(18,2),
  transaction_customer_id STRING,
  kamsoft_program_id STRING,
  estimated_compensation_value DECIMAL(18,2),
  kamsoft_program_name STRING,
  rep_comments STRING,
  transaction_product_bk STRING,
  sales_type STRING,
  date_end_discount_packet DATE,
  date_corrected DATE,
  transaction_time_id TIMESTAMP,
  additional_info STRING,
  purchase_type STRING,
  transaction_customer_bk BIGINT,
  sell_in_volume_before_correction DECIMAL(18,2),
  sales_time STRING,
  date_purchase DATE,
  estimated_order_value_exfactory_price DECIMAL(18,2),
  product_objections STRING,
  distributor STRING,
  discount_packet STRING,
  transaction_source STRING,
  estimated_order_value_ex_factory_price_after_compensation DECIMAL(18,2),
  internal_comments STRING,
  date_distributor_sales DATE,
  transaction_row_id STRING,
  psdt_akt_synch TIMESTAMP,
  chain_customer_name STRING,
  chain_order_id STRING,
  volume DECIMAL(18,2),
  transaction_product_id STRING,
  order_status STRING,
  expiry_date DATE,
  global_id STRING,
  batch_number STRING,
  order_id STRING,
  data_delivery_date DATE,
  date_start_discount_packet DATE,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd')