CREATE TABLE chdaa_prd_lz_emea.emea_curated_disc_ceec.ceec_gen_marketing_view_m360_mapping (
  key4 STRING,
  corporation STRING,
  year_quarter STRING,
  cc_country STRING,
  otc3_description STRING,
  sales_value FLOAT,
  cc_product_id STRING,
  country STRING,
  time_id DATE,
  cc_brand_name STRING,
  nfc1_description STRING,
  otc4_id STRING,
  cc_manuf_secondary STRING,
  cc_manufacturer_name STRING,
  otc2_id STRING,
  marketing_source STRING,
  manufacturer STRING,
  pack_size STRING,
  year INT,
  day_of_year INT,
  market_brand STRING,
  nfc12_id STRING,
  year_month STRING,
  nfc1_id STRING,
  otc4_description STRING,
  nfc12_description STRING,
  otc1_id STRING,
  pack STRING,
  key1 STRING,
  key2 STRING,
  product STRING,
  nfc123_description STRING,
  manufacturer_count INT,
  nfc123_id STRING,
  general_segment STRING,
  channel STRING,
  form_1 STRING,
  week_of_year INT,
  key3 STRING,
  otc3_id STRING,
  otc1_description STRING,
  manuf_secondary_count INT,
  otc2_description STRING,
  sales_volume FLOAT,
  ETLIsDeleted BOOLEAN,
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://curated@zpdatacoresadpemea.dfs.core.windows.net/discovery/ceec/ceec_gen_marketing_view_m360_mapping'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')