CREATE TABLE chdaa_prd_lz_emea.emea_quality_enr_bnlx.dim_prepare_ch_customer_enrichment_dimension_be (
  `0cust_grp5` STRING,
  `0cust_group___t` STRING,
  `0price_grp` STRING,
  customer_sap_customer_city STRING,
  dcustgrp3___t STRING,
  `0salesorg___t` STRING,
  `0cust_grp1` STRING,
  `0cust_grp2` STRING,
  `0division___t` STRING,
  customer_country_code STRING,
  customer_status STRING,
  customer_main_sap_customer_code_1 STRING,
  customer_organization STRING,
  customer_sap_apb_code STRING,
  customer_sap_customer_country STRING,
  dcustgrp1 STRING,
  customer_employee_name STRING,
  dcustgrp1___t STRING,
  `0cust_sales___t` STRING,
  sap_customer_code_trim STRING,
  dcustgrp2 STRING,
  `0salesorg_comb` STRING,
  customer_sap_customer_name STRING,
  `0cust_group` STRING,
  `0distr_chan___t` STRING,
  customer_channel STRING,
  `0distr_chan` STRING,
  customer_sap_customer_code STRING,
  `0cust_sales` STRING,
  dcustgrp4___t STRING,
  dcustgrp5 STRING,
  `0cust_grp4` STRING,
  `0cust_grp3` STRING,
  customer_employee_cwid STRING,
  dcustgrp2___t STRING,
  customer_cluster STRING,
  customer_sap_customer_zip_code STRING,
  dcustgrp5___t STRING,
  dctyspcod STRING,
  `0salesorg` STRING,
  dcustgrp4 STRING,
  `0distr_chan_comb` STRING,
  `0division_comb` STRING,
  dctyspcod___t STRING,
  dcustgrp3 STRING,
  `0cust_sales_combined` STRING,
  `0division` STRING,
  ETLLastModifiedDate TIMESTAMP,
  ETLLineageID STRING,
  ETLIsDeleted BOOLEAN,
  ETLChecksum STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/enrichment/bnlx/dim_prepare_ch_customer_enrichment_dimension_be'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')