CREATE TABLE chdaa_prd_lz_emea.emea_quality_enr_bnlx.prep_fact_sap_sd_orders_nl_remove_prod (
  ETLLastModifiedDate TIMESTAMP,
  ETLChecksum STRING,
  `0dsdel_date` DATE,
  `0lst_a_dd` DATE,
  `0soursystem` STRING,
  dfksta STRING,
  `0sched_line` STRING,
  portfolio_management STRING,
  `0reason_rej` STRING,
  dorqtybu DOUBLE,
  `0subtotal_1` DOUBLE,
  `0dlv_sts` STRING,
  rls_auth_sid STRING,
  `0s_ord_item` STRING,
  `0doc_number` STRING,
  `0material` STRING,
  `0doc_type` STRING,
  `0plant` STRING,
  `0ship_cond` STRING,
  daedato DATE,
  `0gt_bsarksd` STRING,
  `0doc_date` DATE,
  `0net_price` DOUBLE,
  `0material_short` STRING,
  `0billtoprty` STRING,
  `0ship_to` STRING,
  `0cml_cf_qty` DOUBLE,
  `0fiscper` STRING,
  `0so_i_cnt` DOUBLE,
  `0sold_to` STRING,
  `0overall_st` STRING,
  `0salesorg` STRING,
  `0payer` STRING,
  derdatoh DATE,
  `0comp_code` STRING,
  derdato DATE,
  divestsna STRING,
  dflsta STRING,
  `0logsys` STRING,
  dnetvallc DOUBLE,
  `0net_value` DOUBLE,
  ETLIsDeleted BOOLEAN,
  ETLLineageID STRING)
USING delta
LOCATION 'abfss://quality@zpdatacoresadpemea.dfs.core.windows.net/enrichment/bnlx/prep_fact_sap_sd_orders_nl_remove_prod'
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 0 days',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.logRetentionDuration' = 'interval 0 days',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')